
Robert Mason
:doctype: book

== Chapter One

The annual meeting of the Autonomous National Alliance of Leagues was even more tense than usual, Kimberly Telly mused.
Perhaps it was the fact that their champion, Ted Easterly, had gone missing months ago.
Without his valiant posts at birdsite.io, the fortunes of the Alliance had collapsed almost immediately.
Apparently, hashtags really were the problem facing the movement- more than business fundamentals or network effects, the league had been sustained by generous souls willing to say #ProRelForUSA.
Once that had stopped, the clubs had begun to leave.

Of course, the fact that the chairman of the board was holding a gun to his head wasn't helping the mood much either. 
If he could just wait for everyone else at the table to collapse first, he could walk free.
He just had to survive until then.
Just had to _not_ get shot.

"Well... certainly, we've lost our primary marketing asset, one of our most reliable revenue sources, and any media buzz," the chairman burbled.
"But the people must be on our side!
We've stuck true to our principles!"

Telly shook his head.
"The only people who are still following us are three podcasters who all live in Chattanooga."

"The ones who sent us hate mail every day that claim we're ruining their lives and destroying the movement entrusted to us?"

"Yes, them. It is nice to have somebody who cares, at least."

The room went quiet for a full minute.
Finally, the chairman cleared his throat.
"We could put out another book list-"

"What we need is money," Telly interjected.
"Almost nobody in this room has paid their bills."
"Everyone pays up today, we can clear out a lot of outstanding debts to hotels and liquor stores and referees or whoever else we've been stiffing and can move on and get the season going again smoothly.
Maybe we could even run an entire season where nobody commits any federal crimes!"

"Just so long as that doesn't include all of those graphic designers from the clubs the league ran?" the chairman asked.

"Sure, technically those clubs went bankrupt, and I'm still doing business with you, so we're well past the point of being concerned with petty moral obligations," Telly said glumly.

One man cleared his throat at the corner of the table.
"The soccer side of the business is not making money regardless of us paying our bills.
If we're going to get up to sustainability, we're going to have to start getting more creative."

"I agree with him!" another voice chimed in.

Telly groaned.
Larry Gary was a tech mogul in the worst sense of the term: disruptive and amoral, but without a billion dollars to show for it.
Every so often, he appeared to remember that he was running a soccer team- but those brief glimmers of lucidity were becoming fewer and farther between as the months ground on.
How exactly he had made a successful tech business was anyone's guess- Telly suspected that he had found it fruitful to repeatedly pull investors off of the street, but he refused to spend any of his precious time digging deeper into that fool's errand.

Worse still, Larry Gary's wife Lesley had recently left him.
Nobody could quite be sure why, but Larry had since taken to wearing a sockpuppet on his hand that he had named after her.
Legally speaking, the sockpuppet owned a second football team and had a vote in all board matters.
When Telly had attempted to challenge this, the chairman had vetoed it- contingent on a promise that the sockpuppet would never vote to oust him.

"What if we all simply ran good soccer clubs?" Telly asked.
"I've done it for ten years.
Practically pays for itself, almost, whenever we don't get bored and call up La Liga sides to see if they want to hang out in the US.
Maybe we could even have an entire season where nobody commits any federal crimes!
What do you all say?"

"Not nearly enough money for as quickly as we need capital," Larry said.
"We're going to have to get really creative if we're going to move the cash we need.
Trust me.
I've done this six times before,
I can certainly do it again."

"Larry's been doing this for years!" Lesley chimed in.

Telly glanced around the table.
The traveling salesman was hanging on Larry's every word.
George looked calm and not at all like he wanted to drop somebody into a toilet, which was practically raving approval coming from him.
The chairman was stroking his chin in thought, while all of the new members of the board looked like they were intrigued.

Whatever Larry was planning was going to carry the votes.
Now Telly had to both not get shot and avoid getting sent to jail with the rest of these people.
It was bound to be an even longer season.

== Chapter Two

Many believe that there are groups associated with or even fueled by powers fell and dark alike.
Many who hold this belief are certain that soccer supporters are deep in with such groups.
Some believe these powers to be of the devil.
Others, of ghosts.
Still others, of perhaps the old gods, the pagan deities.
But of course, we are not superstitious, so we know better.

Or do we?

Arise, Hephaestus!
Come forth, oh craftsman of the volcanoes!
Bring forth your power for our ritual.
Alight into Detroit with your grim power, forge victory for our club, smite the remnant of the Alliance in our home!

The hivemind of goths completes their dread assembly, the mountain bursts forth, snug squarely between stadium and train tracks.
The coin for smoke is no more, but the smoke becomes ever more bountiful.
Northern beacon, shine forth and smoke out all who face us.

The ball slots home, the stadium erupts with the clamor of crosstown dominance.
The grenadiers drop their offering of fish into Hephaestus's mount, bagging well the additional gift of a human unheeded.
Hephaestus responds with his gift, an eruption of smoke unlike any other seen in the game.
Billows rush down the east and over the pitch, covering every square meter in a fog of war Sun Tzu could not fight through.

"This is ridiculous," George grumbled.
"How is one to even sniff out the game through this?"

A joyous crowd takes no heed, continuing to sing and hurl abuse as the sun itself is blotted out.
White-clad opponents stumble and struggle to retain their footing.

"FUCK YOU! GET UP! YOU'RE NOT EVEN HURT! FUCK YOU FUCK YOU FUCK YOU!" come the screams.
What mooncalves stood against them!
Who would let something as small as crippling black smoke prevent them from running and playing at full speed with perfect situational awareness?
Certainly not their own players. 
No, only the opposition could be so senseless as to lose any capability in volcanic fog.

Again the ball is scored.
And again.
Every time, grim Hephaestus's handiwork replays again, to much the same scene.
Every time, George plots vengeance upon his tormentors.
The football match may be lost to the traitors who left the alliance, but George would see to their swift end after.

== Chapter Three

John looked at the expansion projection list, kneading his temple.
He was supposed to go on a podcast with 829 followers on Birdsite later this afternoon and discuss expansion, which would be a pivotal PR point before finalizing numbers with the league's sponsors to give a much-needed shot in the arm on revenue later.
The problem was that it was dubious whether _any_ new teams would be starting this year and taking them above the national minimum of 8 teams in the league.
What on earth was he supposed to even say under these circumstances?

A knock sounded at the door.
"Come in," John said.
Larry Gary entered the room and sat on the other side of his desk.
"I'm glad you're here," John said.
"I could really use some of that Harvard brain of yours on this problem."

Larry craned his head to take a look at the monitor.
"Not very many in the confirmed column, are there?" he asked, frowning.

"Not for this year," John said.
"We have plenty of groups looking to play two seasons from now, but next year is pivotal if we're going to get things back on track.
We need to build up a head of steam, and currently we're just always around the corner from that."

"Should be an easy fix," Larry said.
"I've got plenty of Silicon Valley experience in going fast and disrupting things.
All you have to do is present the facts a little bit differently."
Larry grabbed a rolodex labeled "expansion contacts" off of John's desk and flipped it open.
"Like look at this, you have... 16 total contacts?
Wait, you've been working on this for 2 years and you only have 16 names?"

"It's difficult to find people who will return my calls after the unpaid bill stories leaked out," John said defensively.
"Every single one of those is a good, active contact!"

"OK.
OK.
That's perfect, actually," Larry said.
"So you can tell them that you're in active conversations with 16 different markets and that they're very promising contacts."

"I said contacts, not markets," John said.
"And some of them haven't gone very deep- just a day of drinks and talking to them about the open system.
Some of them are partners or live in the same city."

Larry lit up.
"Well, a contact who you get drinks with is the only kind I really care about!
Anyway, just say they're all active market discussions.
We're an open system. 
In theory every single one of them could start up their own club or link up with somebody else to do it, right?
And every club is its own market.
It's not really a lie, it's just the most optimistic scenario possible, which is what everybody who still believes in the concept of 'independent soccer' wants to believe in anyway."

John pursed his lips and nodded.
"That could work.
It would be nice if we had more confirmed expansions in the meanwhile."

"Why is everyone waiting another year?" Larry asked.

"Cashflow issues or organizational readiness.
There's only so many people at these groups and it takes time to find a stadium, hire technical staff, make sure housing is worked out properly, and so on.
If you rushed some of them they might struggle to even make payroll on no amenities."

Larry leaned back and looked at the ceiling.
"You just need a little capital to make those sorts of problems go away," he mused.

"Which is what we're all short of," John said.
"It wouldn't hurt to get some of those expansion fees- sorry, mandatory share purchases- in a little sooner.
Heck, if we had more teams in I'd love to pocket some exit fees even more."

"That really is my favorite aspect of the system," Larry mused.
"You have to forfeit your shares if you leave and you pay more for that privilege than you paid to enter the league in the first place.
I think we might actually be the first company in the world to be making bank on what is technically a negative valuation.
I'm already dreaming up other applications for that."

"Focus," John said. 
"We need to make money now."

"Easy fix," Larry said. He leaned over again and punched in one of the numbers that was listed as joining the league two years from now.
"Ivan!
Hey, it's Larry calling on behalf of John.
Yeah, about next year- right, cash on hand- listen, the chairman and I were talking and he has your back.
Mhm.
Right, just like when they injected money into Snag Village when they ran out midseason- you get into any trouble that first year and he'll keep you afloat.
No, it's- what if we knocked off 20% of your expansion fee if you did it a year early, too?
Right, I meant the mandatory share purchase, there is never an expansion fee when you're inserted into ANAL.
OK! Great, it's a deal."
He hung up and turned back to John.

"You do a few more of those and you'll have your shot in the arm and that confirmed club count will be way up," he said with a grin.

The silence stretched out between the two of them before John finally spoke.
"Did you actually confirm with the chairman that he was good for that?
You know how badly his wife took him to the cleaners during that time period when we weren't paying the r-"

"Relax," Larry said.
"It literally doesn't matter whether they collapse at the end of the season and go out of business entirely.
All that matters is that they _start_ the season when we hand in the team sheet to the federation and while we talk to sponsors.
It's basically like check kiting, except the government would be fine with soccer dying entirely and so this is legal."

John bit his tongue.
It was stupid, and maybe it would kill the league, but by the time that happened he probably would have been fired by the chairman anyway.
Might as well roll with it while the money wasn't as bad as it could be.

John gave Larry a smile that didn't reach up to his eyes.
"Thanks, Larry," he said.
"If you could get out of here, I need to call into that podcast now."

Larry nodded and walked out.
As the phone rang, John noticed an old post-it note out of the corner of his eye.
_Find out exactly where Larry Gary is getting his money from._
Perhaps some question were better left unanswered.

== Chapter Four

The US Soccer Federation's disciplinary representative furrowed her brows at the footage that was being shown to her, idly running a finger along her pearl necklace.
"I understand your concern," she told George.
"Unfortunately, there are no Cup rules against blotting out the sun via smoke called from a dark ritual invoking ancient Greek deities, even if the smoke did reach the field of play."

"It's ridiculous!" George fumed.
"They sabotaged the game.
How are we supposed to play through that kind of darkness?
They have been out to get me since I first had my favorite boy try out for them. You have to put an end to this!"

The representative inwardly sighed.
"Well, I suppose I could always call for a committee ruling on the spirit of- wait."
She leaned in and turned up the volume, listening closer to the feed.

"...NOT EVEN HURT! FUCK YOU FUCK YOU FUCK YOU!" came in louder on the replay.
The color drained from her face as she instinctively clutched at the necklace to give her hands something to do.

"Oh my," she said.

"Yes, the language-"

"I've simply never heard such a thing at a sporting event," the representative gasped, feeling fainter by the minute.
"This is simply terrible!"
The camera panned, showing a banner depicting a bear shitting in the woods.
"_Dear me_."
Whoever these Detroit people were, they weren't as bad as this George person was saying.
They were obviously far, far worse.
The last time she had seen an animal poop had been at the zoo, after which she had banned her children from returning for the sake of their own eyes.

George stared at the swooning woman as she crumpled over on her desk from the shock of the stimulation.
After taking a moment, he gently pushed her off the desk and sat at her computer as she hit the ground with a _thump_.
Access to the company directory... floor maps... everything he needed to go find somebody who could get something accomplished.
Liberating the representative's ID badge from her, he used it to activate the elevator and send him up towards the C-level suites.
He hadn't been able to get an appointment with the president of US soccer, but perhaps showing up unannounced could fix his woes.

== Chapter Five

Brian flipped his laptop end over end, exasperated.
"I've had it with these people!"

"What's the matter?" Larry asked, eyebrow raised at the miraculously unbroken machine.

"It's our marketing strategy," Brian said.

"I thought we didn't have any money left for marketing?"

"Right- it's all podcast interviews, a dozen Twitter accounts that I run, and editing Wikipedia to match our press releases," Brian explained.
"And that last part is the problem.
I'm arguing with this @CelticTiefling69 person who apparently edits half the pages for the Alliance and she's reverting all my edits!"

Larry nodded.
"What's even the point of a public resource like Wikipedia if we can't just make it a terse word vomit of all of our own messaging?
They're abusing the common good."

"EXACTLY!" Brian exclaimed. 
"I just can't reason with her anymore.
If I open another Wikipedia account then they'll ban me, and if I use any more of my Birdsite accounts to shout her down they'll figure out that I'm running all of them!"

_It might help if you hadn't included "Run by Brian" on half of them while making the exact same arguments on the other half,_ Larry mused.
Still, it was clear that letting this go wouldn't do.
If they couldn't salt Wikipedia, they might actually have to spend money on real marketing- and where was that going to come from?
He was already "forgetting" to ask ambulances to be available at his games so that it wouldn't cut into his top shelf liquor budget; there weren't many places left to cut costs.
Well, he'd just have to handle it himself.
Again.


----
BIRDSITE.IO
>> WELCOME BACK, NUTAVENUEKING <<
ENTER COMMAND > DIRECT MESSAGE
WHO? > CELTICTIEFLING69
ENTER YOUR MESSAGE BELOW...
----

@NutAvenueKing: Hey, I'd like to talk about what it would take to come to an understanding around our presence on Wikipedia.

@CelticTiefling69: Stop making edits from a hydra of sockpuppet accounts and stop citing your own PR statements.
You've all fallen through on so many promises that they're blacklisted as being acceptable as the sole source for a statement in an article.

Larry pursed his lips. 
It was true that the league had been _ambitious_ in their messaging in years past.
No arguing that one on its merits.
Maybe a bribe could work.
But how do you bribe the kind of nerd that would willingly deal with editing Wikipedia day to day?
_Information_.
Perfect.
He'd get on her good side with a few leaks.

@NutAvenueKing: You know... Flamingo Flight FC was going to be one of our first ANAL teams before the Alliance had its delayed launch.

@CelticTiefling69: Sure, OK.

@NutAvenueKing: In fact, they're working on coming back and joining us now.
They're very excited about what we're doing.

@CelticTiefling69: Why would anyone spend money to join a league that forgets to turn on the cameras for a stream at least every other week?
I don't believe you, and I don't care about any of this.
Leave.

@NutAvenueKing: Look, just tell me what you need in order for us to get more of our messaging out on Wikipedia.
We're just trying to help you with maintenance!

@CelticTiefling69: What I want is for you to stop treating it as a marketing arm and to go figure out how to fix your failing soccer business.
Leave me alone!
_Error Discontinuus_!

----
BIRDSITE.IO
DM WITH CELTICTIEFLING69 ENDED
YOU HAVE BEEN BLOCKED BY CELTICTIEFLING69
ENTER COMMAND > QUIT
----

_I wonder what that meant,_ Larry wondered.
His phone somehow felt chilly.


== Chapter Six

Cynthia Prism typed furiously at her computer, switching between windows and firing off emails in a hotkey-driven blur.
Every so often, somebody would misinterpret the current state of soccer in the United States as dozens of individually greedy stakeholders each trying to maximize profits in their own little fiefdoms.
But that couldn't be farther from the truth.
The reality was that a few elected officials in US Soccer controlled the entire thing, controlling the rise of empires and destroying grassroots movements with a few emails.
With just a few more days' work, she could finally close up the chapter on the recently deceased Promotion and Relegation Organization of Leagues, Academies and Players for Soccer Excellence.

Emails sent, she stood up and began to stretch.
Now if only she could wield the same level of power over the real enemy to her ambitions: professional cornhole.
It was hard work enforcing the bylaws and minimum standards to the letter, but somebody had to wield the rubber stamp.
As she finished working out the kinks in her back, the door opened- and in walked a vision.

The man walking into her office had the mustache of a powerful, sexy walrus.
His graying hair gave him the appearance of a distinguished, experienced man.
And the rest of his body- almost beyond description.
This wasn't a mere dad bod- that descriptor could never suffice for him.
No, the man before her had a _daddy_ bod.
Cynthia couldn't help herself- most powerful woman in the sport or not, she trembled a little with desire at first sight for who she estimated just might be the sexist man alive.

"My name is George, and I need to speak to you about a grave injustice," he said.

"Cynthia," she said.

George brought out his phone and once more brought up the video of the volcano smoking out the entire field, explaining to Cynthia what had occurred and all of the years of torment his sworn foes had put him through.
She barely listened to it all, stealing long glances at his body as he ranted and raved about one thing after another, only a few of which were really related to the matter at hand.
_Handshake agreement?_
_I could give you a good shake._

Finally she realized that he had stopped some time ago while her eyes were still wandering, and he was expecting a response.
She looked up and met him in the eyes.
"I can promise you that I'll fully correct the injustices I've seen," she said, voice edging into the sultry.
"We should definitely schedule a meeting so we can unify our interests."

"Yes!
I would like that very much.
We can finally squeeze the life out of these bloodsuckers."

_I'm certainly going to squeeze the life out of_ something _here_, she thought.

== Chapter Seven

_Some time ago_

Benjamin Quick sat on his knees before commissioner Donovan Grabber.
"So," the commissioner murmured, "you finally realized that working for your precious national team ultimately means working for me."

Ben cast his eyes downward.
A mere month ago, working with Grabber would have been unthinkable, equivalent to cavorting with the devil.
That was before Ted had broken up with him and made it clear that promotion and relegation was more important to him than their life together.
He took a deep breath, then lifted his eyes up to the commissioner.

"I'll do anything you ask, so long as you empower me to take my revenge," he said.
"I want to see Ted dead before me."

"His foolish ambitions were already a shambling husk," Grabber purred.

"No.
I want _him_ dead.
Not his dreams, not his ideals- him."

"Of course," Grabber said.
He was hardly above working with murderous psychos or taking their money.
Hell, a lot of them bought tickets.
"Stand.
In order for you to accomplish your goals, you're going to need power... significantly more power."

Grabber wordlessly led Quick to an elevator that took them all the way to the basement of the League's headquarters.
Deep within the bowels of the building, there was a machine with a man-sized glass tube.
Many power cables and hoses fed the curious monstrosity.
Grabber gestured for Ben to enter the tube.

"As everyone knows, leagues rise and die based on how mean people are on the Birdsite," Grabber noted.
"The Alliance will soon fall to the veritable flood of negative posts we send their way, and then the reform movement shall be crushed.
This Collector of Crap Kontent will-"

Ben suddenly collapsed from the force of the world's largest involuntary groan, the universe demanding counterbalance for contrivance.

"Ahem. 
It will collect all of the worst soccer-related content from the birdsite, convert it into gaseous form, and then flood the chamber with it.
You'll become a human embodiment of the worst of the scene, a potent weapon able to purge the sanity of any who read your posts."

Ben picked himself up and stood up tall.
"Let's do this, then."

Grabber flipped a switch.
The machine connected up to Birdsite and began to pull down every post it could from reform-minded hashtags, from anti-reform accounts, and a few corporate accounts for good measure.
A loud humming filled the room as condensers rendered the posts into physical form, then superheated them up to eye-watering temperatures.
The gas began to flow in as Ben bit his tongue to avoid crying out in case it hurt.
Soon the entire room was obscured, with neither party able to see each other.

Improbably despite the temperature, the process didn't hurt at all.
Ben actually experienced it as a sort of cool breeze.
Finally, the gas cleared, and the tube opened up automatically.
"Gotta be honest, Don, I don't feel any different at all.
Nice way to cool off during the heat, at least."

Grabber frowned.
"Stay in there another minute please," he said.
The process was supposed to cause some level of mental and physical decay in exchange for granting power, but Quick seemed to not be affected at all.
Grabber checked the data inputs and shook his head.
Quick's own posts accounted for at least 20% of the data input.
That was never going to work.
What other data sources could he add in?

He pulled up the data sources tab.
Pro-monarchy Birdsite, that should be good.
Everyone who was still interacting with Joe Rogan online, for or against, probably had no filter.
It was still missing something.
He scrolled down until a single item stood out, simply labeled "GAMERS".
Without hesitation, he added it to the queue and immediately fired up the machine again.

This time, Ben's screaming was heard loud and clear through the smoke.
Plasma danced along the glass, the supercharged energy well beyond limits that would kill most people.
"STOP IT STOP IT PLEASE I BEG OF YOU!" Ben shrieked.
Grabber simply grinned.
He hadn't lifted his boot up to show mercy to any other fan who had come in begging him for assistance, and he certainly wouldn't start now.

Finally, the smoke cleared.
Ben's skin had turned a sickly green hue, a forked tongue flicking out nervously.
"Whaaaaat have you donnnne to meeeeeee?" he hissed.

"I have given you exactly what you asked for.
The power to destroy those in your path."

"I can feeeeel the sssstrength in my body," Ben said.
"I will killll Ted with thisssss powerrrr."

"That's all good and well," Donovan said.
"But I mostly need you to keep posting things on the Birdsite that will make the reform movement look stupid."

"I willll argueee your caseee."

"_Hell_ no.
I need you to keep arguing the reform side, much like how you have been, only moreso."

The forked tongue went in and out as Ben considered.
"Youuu do not waaant me to publicly ssssswitch?"

"Are you kidding?
You and Ted as a team were the third best thing that ever happened for us in terms of the movement looking stupid, and that's only because the Alliance and the Deltas exist to take the first two.
Now come on, we have a board meeting to get to."

* * *

_Months later..._

Ben stood triumphantly over the bodies of Noruhl and Easterly, then dialed out to the commissioner.
"Iiit isss finissshed," he rasped.
"The traitorsss are finally finissshed."

"Good, Benjamin.
I knew I could count on you.
Now, listen.
We've finally located where one of our other old friends has left around a certain disk.
It could be a disaster if the wrong person got ahold of it- and right now the Alliance has the only copy."

Ben licked the air, taking in the aroma of his kill.
"Ssssurely you cannot mean- but he issss not even in the countryyyy."

"Correct.
He doesn't give a damn about the thing.
But rumor has it one of the other thorns in our side is attempting to sneak their way in and steal it."

Ben snarled.
"Theyyy will not even live to see this dissssk, let alone usssse it againsssst usss."

== Chapter Eight

"Well, I have to admit I'm sold on your values," president Jacob Sikadapap of the Club-subordinate Oligarchy of Controlled Kleptocrats said to George.
The Oligarchy was considered to be one step higher than the Alliance in the US system. 
As long as George was making trips out anyway, it was the perfect opportunity to solidify a step up.

"So, you're prepared to welcome in my team as the newest member of the Oligarchy?" George asked.

Jacob gave a winning smile and held out his hand.
"More than prepared to welcome any refugees from the crumbling Alliance.
Our gain is yours."

George stared deep into Jacob's eyes and took his hand firmly, shaking it vigorously.
"The pact is sealed," he said gravely.
"We have grasped each other's flesh and known it."

"Yes, of course.
We simply need to get the paperwork together in a month or so," Jacob laughed nervously.
"Then you'll be all set."

"Our obligations are set in stone," George intoned as he continued to rattle Jacob to the bone.
"We will together destroy our enemies."

"Yes, ironclad, please let go of me," Jacob gasped.
At last, George relented, then turned to his firstborn son and pride and joy, Steven.

"We are going to get you to play in an even higher level now, boy," he said.
Steven beamed with pride.

"Of course, papa!" he said.

"I'm so excited, papa!" someone else said.

"Yes, I'm also looking forward to what I can do next!" another one said.

George's wonderful wife had birthed many children. 
One of them even lived up to expectations, usually.
But it was useful to have spares.

== Chapter Nine

John calmly got up from his desk, picked up his phone, walked over to his fishtank, then dropped the phone in.
It sank to the bottom, not a single bubble of air leaking out of it.
A testament to the genius of engineering.
But genius was cold comfort when it paired with madness, when the consequences at last came home.
All that John had now was the knowledge that nobody could call him anymore, at least not for a few days.
He would have the excuse that he had accidentally dropped his phone in the fish tank and simply couldn't receive or make any calls.

The door opened, and Larry walked in.
"I told you so!" Larry thundered.

"Told me so?
This was all your bad idea to begin with!
'It doesn't matter whether they collapse at the end of the season', that's what you told me.
Well now every single new club we added this year on your recommendation has collapsed in the _middle_ of the season.
So now that we're in this pickle, what exactly is your plan, Larry?"

"It hardly matters that they collapsed in the middle, either," Larry said nonchalantly.
"We started the season over the minimum of 8, we kept sanctioning that way.
We won!
Now we can just do it again next year.
I've got a lot of experience with this, all we need to do is find another round of investors and keep the party train going."

"Oh yes, brilliant," John seethed.
"We have all the press of being the league that can't pay the bills already.
Now we're having to reconfigure the entire season with 2 months left because we lost a ton of teams and have to alter history to compensate.
Every investor with money is asking why they shouldn't go to the Oligarchy instead, and the ones _without_ money are asking for more of your special deals.
And all this without you even being up to date on your dues!"

Larry was caught up short.
He closed his eyes, took a deep breath, then re-opened them.
"That's a defamatory statement and I'm going to have to insist that you stop right now."

"Defamation," John asked, gesticulating incredulously.
"There's nobody to defame you to.
We're in front of a bunch of goldfish."

"Yes, and they have attention spans and fiscal sense comparable to my usual investors, so I must insist that you stop using such language in front of them.
The Alliance has a flexible payment schedule and my clubs are allowed to pay our dues as we see fit."

"Provided you're paid up before each season, yes. 
You haven't paid a cent since this season started, and that's besides the six figure loan that Inequity Football made last year that you still haven't paid back.
You're technically not even a member in good standing.
I could have you expelled from the league right at the end of the season if I wanted."
He narrowed his eyes.
"In fact, maybe I should."

"You can't do that," Larry said.
"I am a class A shareholder in this organization and even if I don't pay my bills, provide consistent healthcare and workers comp for my employees, allow them to get injured without coverage, post NDA-covered material to the Internet, allow a team doctor to sleep in their car because they haven't been paid for months, host games without ambulances, operate three separate ponzi schemes that resemble football clubs, or otherwise fulfill any of my contractual obligations, you can't expel me from the league."

Unbeknownst to either party, the fish in the tank was speaking simultaneously with Larry:
"1001 Football Crimes is a work of fiction.
The story, all names, characters, and incidents portrayed in this production are fictitious. 
No identification with actual persons (living or deceased), places, buildings, and products is intended or should be inferred."
Regrettably, the fish's metatextual enlightenment would never be known to anyone within its world, as the language of a fish is impossible to convey to humans in a way that could be comprehended by them.
As the sole being in the universe who was aware that its world was in fact a form of cosmic absurdity, it formed a sort of supreme Cassandra, the only one who could have explained that within a short time, you, the dear reader, would read the end of your experience of this book, consigning all the beings within to a sort of cessation of existence.
The memories that would echo the original would depart from the reality of the work, and only a sort of kafkaesque distortion would live on within your own brain.
The fish was forced to know this, to know that at least in this world, some creatures _could_ go to a sort of afterlife.
But this one was doomed, and need I even explain why?
No- let it be left unsaid, so that the fish's task not be subverted, its damnation not made futile.
Let us leave the tank.

"If your bills are not paid by the end of this week, you're expelled," John said.

"We'll just see about that," Larry said as his phone began to ring.
Lesley was calling- it was always nice to hear from your literal partner in crime.
It must be because she was coming back to him!
_We're going to see you fired, John. And when we do, I'm going to be the king of this league._

== Chapter Ten

It was a hot day in Chattanooga, Tennessee, and George was feeling testy.
The referees had been mistreating him and his team all year.
Why should he even be dealing with it anymore?
He had a handshake agreement with a new, much better league anyway.
It was time to send everyone else down to earth while his star shone brighter than ever.

George's team had been steadily absorbing all of his pent-up rage.
It was hard for them not to, in all fairness: every time a coach failed to play his beloved firstborn son, Steven, the child who had made him a father, that coach was promptly fired and George took over.
When coaches were present, George would angrily berate them anytime there wasn't a win, or anytime there were too few chances for Steven to score.
The opportunities afforded to Steven must be unlimited as the stars; this was the guiding principle of his team.
And of course if the spares happened to shine a little that was fine too.

On the field, a challenge for the ball went badly, leading to a scrum of players pushing and slapping at each other.
George was instantly enraged.
This sort of behavior from these Chattanoogans was the sort of thing that could easily escalate to him having to rely on one of his spares- and that wasn't a great idea whether tires or children were in view.
Suddenly, one of the southerners actually punched one of the other players, the pushing and slapping intensifying in its wake.
Honor demanded that George do something about this.
He trundled over to the Chattanooga coach.

"YOU WANT TO GO?" George shouted.
"COME ON!
LET'S GO!
BE A MAN!"

George's opposite number glanced up and down at him, unimpressed.
"Yeah, sure.
You want to go for a race?
40 yards, there and back.
Unlike some teams in this league we actually keep an ambulance on-site with trained medical staff at all of our games."

"COME ON, YOU COWARD!" George gasped, trying his hardest to provoke his opponent into making the first move.
In the background, the grand melee of all slapfights was finally breaking up as the referee displayed card after card to players, the threat of fines sapping the will to continue.

* * *

"Hm, that's odd," I said.
"Tickets for the match against that other Michigan team aren't on sale yet."

"You're not allowed to go there anyway," the traveling salesman reprimanded.
"You have a lot of work to do before we're letting you go.
Demands of the narrative and all that."

"It's my book!" I said.
"I should be able to keep attending matches regardless of the needs of the plot.
In fact I'm pretty sure I'll change the plot so I can watch matches if that's what it takes."

"Let's not get into another tired discussion of which side of the fourth wall this version of your consciousness is on.
We have a lot of work to do against the Kleptocracy still, and we need you fully focused for the good of your own team."
The traveling salesman closed his own laptop and dropped his can of beer into the bin.
"Anyway, I need to go run interference on an investor call for Larry.
Be g- just be yourself but in our favor, OK?"
He walked out.

I bit my lip and switched back to looking at the tickets page.
Why wouldn't they be on sale? 
I looked for a phone number for the team, took a moment, then called it.

"Hello, you've reached Michigan's Professional Soccer Team," a thick Albanian accent responded.

"Uh, hi, this is John, I was hoping to buy tickets?" I said.

"John?
Well, I'm sorry, there aren't any tickets on sale right now."

"Why not, though?"

"Our league has been treating us very poorly.
Lots of bad calls by the referees, and after our players were mistreated very badly we were given fines and I am not paying them.
So I told them that we will not be playing our next match until they say we do not have to pay any fines."

"Oh.
That sucks.
I really wanted to watch some local football this weekend." 
I wasn't actually local at the time- I was being shipped back and forth between New York and Chicago regularly, with an occasional stopover at league headquarters.
I was putting up with it until I had retrieved what I needed from the league- finding it was taking longer than expected, though.
In the meanwhile, there were advantages to being in a place where everybody would just loudly blab about their plans around people who had no need to know them.

"Well, I'm sorry," George responded.
"We just don't know if we're playing or not."

"When will you know?"

"Sometime later this week."

I hung up the phone and began to spin my swivel chair, faster and faster, the world spinning into a blur, my eyes attempting to track individual objects until all focus was lost.
Later this week, huh?

* * *

_Four days later_

"Hi, this is John-"

"Who are you?
Where are you from?" George asked.

"Huh?
Like I said, my name is John-"

"It's very suspicious that you just keep calling every day and asking like this."

_Yeah, I'll bet that it's suspicious that anybody would actually want to see one of your games this badly._
"I just really want to see some soccer this weekend, what's so weird about that?
Are you going to play or not?"

"You will find out," George said, then hung up the phone.

Oh well.
It wasn't like I could have gotten there anyway.
Something was bothering me about the whole exchange, though.
Why _was_ I so invested?

* * *

"We had a _handshake agreement_!" George thundered.

"Yes, and that was all we had," Sikadapap said.
"Then we found out that your response to your players fighting is to attempt to join in, back them up online instead of condemning them, and then threaten to not play your remaining matches.
I don't know what kind of clown show the Alliance is that you can throw your weight around like this without being removed, but the Kleptocracy has _standards_."

George was so angry he could practically spit blood.
But there was nothing for it.
Now he had to actually play the remaining matches.
He would be stuck within the Alliance until the end.

== Chapter Eleven

The doorbell rang while Larry was in the middle of a call. 
He'd never had much of an opinion regarding the soft, windchime-like tones of the bell. 
They did the job: played a generic little tune that echoed delicately through the whole house, not entirely unintrusive and yet delicately insistent, like a well-trained butler.

And, like that non-existent butler- Larry was good with his money, but he wasn't quite good enough to afford that kind of pointed skill in his staff, so he'd never bothered hiring anyone to fill the role- this chime of the bell carried with it a subtle hint of ominous import.

Something in Larry's life was about to go wrong.

It was a silly thing to feel. Didn't fit at all with the eternal optimist attitude he lived his life by. 
He was a Can-Do, Fake-it-'til-you-Make-it kinda guy. 
If he wanted to make a million bucks from expansion fees, he'd chat with ten team owners a day, give 'em the hard sell with a thousand-watt-smile, and have them all itching to enter ANAL by the end, all without shedding a single drop of sweat, blood, or tears. 
He loved his job. 
He was good at it. 
People liked him.  

But he couldn't shake the sensation of impending doom that little doorbell jingle had given him.

The final tone of the bell faded into a hollow kind of silence that ballooned out to fill the yawning emptiness of the house. 
A chill literally ran down his spine, and that had never happened before.

“Sorry, Jim,” he said into the receiver. 
“I'm gonna have to get back to you on this. 
Appreciate the hustle, though. 
I'll email you the pertinent details.”

He touched his thumb to the “end call” button, slid the phone into the back pocket of his expensive khaki slacks, and took a deep breath.

He wasn't one to back away from a threat. 
And this wasn't a threat. 
It was just the doorbell, for Pete's sake. 
It was probably just someone selling new aluminum siding, or a subscription to some outdoorsy camping catalogue—you know, the folks who didn't have any clue that all the real money to be made was in soccer leagues.

It wasn't Girl Scout Cookie season, either.
So, for sure, whoever was on the other side of that door wasn't anyone who could out-earn him.

Still, a cold lump settled somewhere between his heart and his stomach as he made his way down the stairs. 
Late afternoon sunlight filtered through the cut crystal window of the front door. The rainbow sparks it threw on the hardwood floor and eggshell walls were broken by a vague, crystal-warped figure.

Larry's hand trembled as he reached to unlock the deadbolt.

He opened the door.

A bored-looking reed of a man stood on his front porch. 
He was of middle height, slightly balding, with a thin brown mustache over his lip and squared glasses in rose-gold frames sliding down his long nose. 
He looked just shy of forty, but his impeccable gray suit and small leather briefcase said he aspired to appear older and more authoritative.

He blinked at Larry once upon the door opening, then nodded once, sharply.

“Larry Gary?” he said. His voice sounded like it was made of cardboard.

“Uh, yes. 
I mean, yeah. 
Yeah, that's me,” Larry said. 
Come on, Lar. 
Don't let this little weasel throw you off your game. 
“You're looking for Larry, I'm your Gary.”

He gave a little finger gun action and a wide-yet-lopsided smile to seal the deal, as it were. 
The deal that said, “I'm not freaked out by your doorbell ringing technique.”

The man on his front porch ignored this and opened his briefcase with a crisp snap. 
He pulled a single sheet of thick cream paper from the dark depths, glanced at it through the glasses that were now practically dangling off the tip of his nose, and then handed it to Larry.

“You're being served. Have a good afternoon.”

Larry glanced at the page. 
Words jumped out at him, their meanings at once piercing and numbing. 
_Restraining._
_Court order._
_Divorce._

“Divorce?” Larry said. 
His voice rasped in his throat. 
“Lesley? Hey. Hey, wait a minute, man.”

But the man had already climbed back into his sleek black car and pulled away.

Larry let the arm holding the paper fall to his side. 
Divorce. 
Yes, Lesley had left him, but he'd assumed things would get patched up, somehow. 
No, he hadn't done anything to make that patching happen himself, but who could expect him to? 
He was a busy guy! 
He had millions of dollars to score off unsuspecting soccer team owners. 
Frankly, it was up to Lesley to win him back, right? 
He was a catch!

Divorce.

Fucking hell, the word made him feel something he'd never felt, not in his entire life.

He felt like a loser.

Realizing he was still standing in his open doorway where all the neighbors could witness his fish-like gaping- _catch and release, how insulting_- and humiliation, he swung the door closed. 
The rainbow sparkles fell over his face and dazzled in his eyes. 
He blinked. 
Hard.

When he'd wiped away the stupid tears, he found himself staring at the little sock puppet he'd made of Lesley. 
It sat on the shelf next to where he kept his keys, a little slumped over for lack of internal support, but still smiling serenely at him.

He'd given that puppet real shares in ANAL after Lesley walked out on him. 
Ridiculous and stupid, perhaps, but it had been a way to push away all the bad feelings her leaving had stirred up.

The horrible paper the little lawyer had given him fluttered to the floor.

Before he'd even thought to do it, Larry pushed away from the door and swept the puppet up off the shelf. 
He slid it onto his fist and wiggled his fingers to settle into the articulation point of the mouth.

“Lesley,” he whispered. 
With his other hand, he stroked the twisted yarn of her hair. 
“You'd never leave me, right, babe?”

Sock puppet Lesley tilted a smile at him. 
Her button eyes glinted in the rainbow sparkles.

Then she opened her mouth.

“You're fucking your whole life up, Larry. 
You're throwing it all away on shady soccer deals and blow. 
Anyone would leave you, babycakes.”

Larry ground his molars together. 
“Shut up. That's not true.”

“Why can't you be a wholesome family man? 
Settle down, stand by your woman, take the kids for pizza, all that jazz? 
You're a disgrace, Larrison Garrison.”

“_Shut up!_”

He flung the puppet down. 
It landed next to the divorce paper, where it grinned up at him horribly.

Larry spun on his heel and marched away, back to the stairs. 
He took them two at a time, each footfall thudding hard enough to rattle the pictures on the walls. 
Pictures of himself and Lesley on a date, getting married, on their honeymoon, on vacation.

He stared deliberately at the carpeted rise of the next stair and stomped harder. 
Things were not falling apart. 
Everything was _fine_. 
People _loved_ him.

And he knew just how to show it.

He'd show Lesley—both the real one and the backstabbing one made of a gym sock—how wholesome he could be.

Back in his office, he grabbed his phone out of his pocket and dialed a number he knew by heart.

== Chapter Twelve

George drained another glass of fernet as Laribald Garibald crashed into the bar and took a seat in a seemingly drug-fueled rampage.
Good.
This situation could use some dynamite thrown into the mix.

"That fucking _bitch_," Larry ranted before George could get a word out.
"She thinks I'm totally reliant on her.
Well I'm not.
She thinks she's going to stop what I'm building by just walking away with her shares and one of my teams?
I put this damn league on the social media map!
We'll just start another business.
Start a conversation with John- we're gonna cut him out."

George salivated so hard it was slightly painful, his mouth becoming a fetid pool of anticipation as he thought about eliminating one of the people who had consistently gotten in his way.
He could make use of this.
"All we would have to do is have a vote.
He could be out tomorrow."

"Yes, a vote!" Sockpuppet Lesley shouted.
"We can _all_ vote him out.
And that rat bastard the chairman with him!"

"The chairman will simply veto that," George said as his phone began to buzz.
"We already promised your puppet wouldn't cast any votes against him anyway."
He pulled his phone out- it was a message from Cynthia Prism.

"Got a chance to 'chat' in private tonight? 
I think I could solve your little handshake agreement problem... in exchange for the right payment.
Maybe some quality Albanian meat. ;)"

_How am I going to acquire Sudžuk and get it prepared in time for her arrival,_ George wondered.

"If we can get a room, maybe I could get US Soccer to resolve our issues," he mused aloud.
"Just as soon as I-"

"_Oh I'll get you a room_," Larry said.

"It's really important that I get hold of a good quality sausage-"

"_I'll get you all the sausage you can handle_.
I'll show her exactly what she's missing out on by leaving.
You just wait here and I'll message you which room I get.
I'll leave the door propped."
With that, Larry ran off again without having ordered anything.

George ordered another glass of fernet.
The phone buzzed again some time later- room 401, directly upstairs.
He forwarded the info to Cynthia and headed for the elevator.


== Chapter Thirteen

George fumbled open the door to room 401 as Larry Gary had told him to.
"OK, I'm here buddy.
Now what did you want... to..."
George trailed off as he took in the sight before him. 
"What is all of this?"

The room was covered from top to bottom with pizzas.
Pizzas covered every square inch of floor.
The beds were loaded with pizzas.
Even the walls and ceiling were, improbably, laden with pizza- how they were staying on wasn't clear.
Not a single box was in sight.

And standing in the middle of it all was a stark naked Larry Gary, holding naught but the Coke that had clearly been influencing his behavior to this point.
"Shhhh," Larry said, his well-seasoned breadstick ready with the telltale firmness of one slightly too baked.
"We don't need any words.
All your previous betrayals were from mere handshake agreements.
But we can seal our working relationship with something far more meaningful."

"We really shouldn't," George said, sweating as Larry went for the buttons on his shirt.
_What would my wife say about this debauchery_, he wondered, but couldn't quite say aloud.
His wife didn't have the vision for business that he did. 
That's all this was: business, with a side of revenge.

As the shirt came off and his belt was loosened, George couldn't help himself but to feel Larry's breadstick.
It was buttery smooth, and just the right size- it would go into his mouth so smoothly.
George had gone for many a breadstick in his younger years- he knew perfection when it was in front of him.
It was surprisingly dark, all things considered.
Possibly the result of a little too much time in the heat.

Distracted, he hardly even realized that his shoes and pants had all been removed until Larry suddenly marched him over to the pizzas and shoved him onto them, sliding them across the cheese in one smooth motion before leaning into a deep kiss.
Before he could even properly think about how out of order that had been, George jumped as he realized that Larry had started to touch his prized pepperoni roll.
Larry might have a wide array of pizzas with all toppings around him, but George was a stout Balkan man and knew that the cure for the deepest craving that humanity had was a stout, powerful Sudžuk sausage.

Larry Gary began to stroke the sausage more intently.
"There's something... different about this," he murmured.
"It's not your typical... that is, it feels like it's already filled with-"

But in the meanwhile George had been transported back to his wilder younger days back in the old country.
Old times.
Old lovers.
In a moment he relived what had felt like an entire lifetime with a man who had proved to be another forbidden fruit- Colby Jack, who had seemingly always been semi-hard.

"Jack," George sighed, as if in a trance.

"Filled with jack?" Larry Gary asked, frowning.
That was no state to leave a pepperoni in.
Larry squeezed with furor.
It was time for a good jack off if he was going to get this sausage to the state he really wanted it to be in.
He worked it up and down, giving it a few licks.
All told, it was really quite delicious.
He let more of it into his mouth, showing off the capacity that had made him the class hot dog eating champion 5 years in a row in school.

Finally, the pepperoni surrendered its delightful filling, to the delight of both participants.
It wasn't easy to do so- only the alertness conferred by consuming large amounts of Coke made it possible.
Every time it seemed like there couldn't be any more, another spurt happened.
It was enough to make him wonder if he'd secretly worked through a calzone.

At long last the torrent of goo ended and Larry licked his lips, satisfied, as George gasped.
In 30 years of time with his wife, not once had she showed such aptitude at sausage handling as to leave it in such a state.
He opened his eyes and gazed at Larry Gary.
Both of them were simply covered in cheese now, but neither particularly cared. 
George allowed himself to roll over and settle into Larry's bought-and-paid-for sauce, marveling at what the juices did for his skin.

It wasn't long before Larry Gary decided that it was time for round two and for his breadstick to be handled.
With the wordless understanding that can only be expressed by two titans of business, Larry laid out a generous portion of oil onto George, then prepared for the difficult work of stuffing George's crust.
After all, why should his own stuffed cheesy bread be left in the lurch?
Filling transferral was no easy proposition, but Larry was a deft hand at pulling off doughy maneuvers.
And truth be told, once you had started in on them, you could hardly help but find it addictive to go for just one more- he was an adeptly practiced hand.

But even while ensuring a reciprocal unloading, Larry Gary couldn't help himself. 
While pumping his dispenser in and out to prepare for the crust stuffing, Larry gently stroked George's olives, dabbing the oil from them to his adjacent jalapeno.
He knew he had to be careful with this- it was possible to get too much heat- but he could barely help himself.
Finally, this all proved to be too much, and the crust was completely and utterly stuffed ahead of schedule.
There was a sense of timing to this, and he worried that he had simply loaded it up too quickly.
_I guess it's true what they say- nobody_ does _do it like the Hut after all._
He rolled over to the other side of the king-sized bed, limbs flopping against pizzas as he went.

Tragicomically, and saving the author from the duty of writing some unconvincing aftercare, a nude Cynthia Prism finally made it up to the room, holding on firmly to an early-2000s handheld entertainment system.
"Looks like you boys started the dealmaking without me," she said, raising an eyebrow at the most catastrophic loss of a security deposit that had ever been made.

"That was not my fault," George gasped, panicking.
Larry Gary was not the only man that he needed a deeper-than-a-handshake agreement with- the man's impatience might have cost him the best chance he had at her all-important anchovies!
This was a disaster!

"Well, I suppose you boys could make it up to me," she said.
"You owe me a double battle."

Both Larry Gary and George were surprised to find that they were already prepared to link cables again and participate in a trademark-free entanglement. 
After the brief preparation of a load screen and the button tapping of some menuing, the men's onyx's were able to quickly use harden and tackle her cloister, hammering away until a string shot finale as they retracted.

George passed out face first into the pizzas.
He had simply no idea how he would explain this depravity to his wife later.
But at long last, he had something so much deeper than a handshake deal with the highest levels of US Soccer.
Revenge would be his soon.

== Chapter Fourteen

George fumed at the meeting of the ANAL board.
Cynthia had simply said she would speak to the league "for the good and proper conduct of the game" to prevent him from being banned by ANAL.
She had flatly turned him down in terms of applying any pressure to preserve his handshake agreement, saying that nothing was worth the opportunity cost of doing so.

The meeting was proceeding around him, but George could hardly care.
Most of the time was being spent with Larry alternately arguing with and then making out with his puppet, with the rest of the business being conducted during sobbing fits.
The word "fruit" seemed to come up once every 90 seconds, sometimes chokingly shouted at John. 

Suddenly the doors burst open.
"Securities and Exchange Commission!
Hands up, Larry Gary!
Don't even think about trying to run!"

Larry made to bolt when the doors on the _other_ side of the room burst open, revealing a set of curiously sharklike people on two legs, mouths full of razor-sharp teeth.
"Larry Gary!
We're here to collect!" they shouted.

Larry spun on a dime.
"You can't make me pay what I owe!
That's usury!
Making me pay you back is usury!"

George watched what happened to Larry, numbly fascinated at the scene.
The boy would get to play another year, and the spares would keep supporting him.
That would have to be enough.

For now.


== Chapter Fifteen

Two weeks ago, I found the disk- and in all the confusion with the sharks, I had a chance to slip into the room with the Alliance's mainframe.
It was guarded by a keypad lock, which wasn't really an obstacle when management insisted on a code of "1-2-3-4-5-6-7-8" so that they'd always be able to keep the systems running.
From there it was easy enough to quickly slot the disk in.
"RUN NYEH.BAT && EJECT", and away we went.
Just needed some time to let it process.

The progress bar reached 80% as the door opened behind me.
"Sssssooooo... I ssseee you fouuund iiit," a reptilian voice hissed from behind me.
"I'll ssssimply relieve you of it before you can do any more damage."

Ben Quick.
"Afraid not," I said, a grin tugging up one corner of my mouth.
"I have a lot more stops to make with this thing."
86%.

"My employersss would prefer that disssk to never be sssseen again," Quick said, walking towards me.
"You can let it finisssh here, but that'sss as far as thisss goessss."
91%.

I slowly reached for my multitool, for all the good it was going to do against lizard boy.
I unfolded it as I spoke.
"Guess one of us is going to be disappointed, then."
Then I turned to you.
Yes, you, dear reader.
"And for only $5500 per goal at the next Detroit Prideraiser, we can make sure that Ben, his bosses, and bigots everywhere are the disappointed ones."
93%.

"You sssimply cannot defeat me by appealing to the power of friendssship," Quick said.
"You ssshall die very, very soon."
95%.

"Probably accurate," I said.
"And I'm really going to hate to be left here hanging for however long it takes until the next campaign."
I turned back to Quick.
"But on the other hand, _if_ we all pull it off... well, your bosses are going to have a really bad day."
I placed my off hand behind me.
100%.

The disk ejected from the computer, spinning into my waiting hand.
Alarms began to sound throughout league headquarters as the building began to rumble its dissent.
Quick's mouth opened, his deadly lizard tongue screaming towards my face-