= 1001 Football Crimes
Robert Mason
:doctype: book

== Chapter One

The annual meeting of the Autonomous National Alliance of Leagues was even more tense than usual, Kimberly Telly mused.
Perhaps it was the fact that their champion, Ted Easterly, had gone missing months ago.
Without his valiant posts at birdsite.io, the fortunes of the Alliance had collapsed almost immediately.
Apparently, hashtags really were the problem facing the movement- more than business fundamentals or network effects, the league had been sustained by generous souls willing to say #ProRelForUSA.
Once that had stopped, the clubs had begun to leave.

Of course, the fact that the chairman of the board was holding a gun to his head wasn't helping the mood much either. 
If he could just wait for everyone else at the table to collapse first, he could walk free.
He just had to survive until then.
Just had to _not_ get shot.

"Well... certainly, we've lost our primary marketing asset, one of our most reliable revenue sources, and any published media buzz," the chairman burbled.
"But the people must be on our side!
We've stuck true to our principles!"

Telly shook his head.
"The only people who are still following us are three podcasters who all live in Chattanooga."

"The ones who sent us hate mail every day that claim we're ruining their lives and destroying the movement entrusted to us?"

"Yes, them. It is nice to have somebody who cares, at least."

The room went quiet for a full minute.
Finally, the chairman cleared his throat.
"We could put out another book list-"

"What we need is money," Telly interjected.
"Almost nobody in this room has paid their bills."
"Everyone pays up today, we can clear out a lot of outstanding debts to hotels and liquor stores and referees or whoever else we've been stiffing and can move on and get the season going again smoothly.
Maybe we could even run an entire season where nobody commits any federal crimes!"

"Just so long as that doesn't include all of those graphic designers from the clubs the league ran?" the chairman asked.

"Sure, technically those clubs went bankrupt, and I'm still doing business with you, so we're well past the point of being concerned with petty moral obligations," Telly said glumly.

One man cleared his throat at the corner of the table.
"The soccer side of the business is not making money regardless of us paying our bills.
If we're going to get up to sustainability, we're going to have to start getting more creative."

"I agree with him!" another voice chimed in.

Telly groaned.
Larry Gary was a tech mogul in the worst sense of the term: disruptive and amoral, but without a billion dollars to show for it.
Every so often, he appeared to remember that he was running a soccer team- but those brief glimmers of lucidity were becoming fewer and farther between as the months ground on.
How exactly he had made a successful tech business was anyone's guess- Telly suspected that he had found it fruitful to simply pull investors off of the street, but was adamantly opposed to spending any of his precious time digging deeper into that fool's errand.

Worse still, Larry Gary's wife Lesley had recently left him.
Nobody could quite be sure why, but Larry had since taken to wearing a sockpuppet on his hand that he had named after her.
Legally speaking, the sockpuppet owned a second football team and had a vote in all board matters.
When Telly had attempted to challenge this, the chairman had vetoed it- contingent on a promise that the sockpuppet would never vote to oust him.

"What if we all simply ran good soccer clubs?" Telly asked.
"I've done it for ten years.
Practically pays for itself, almost, whenever we don't get bored and call up La Liga sides to see if they want to hang out in the US.
Maybe we could even have an entire season where nobody commits any federal crimes!
What do you all say?"

"Not nearly enough money for as quickly as we need capital," Larry said.
"We're going to have to get really creative if we're going to move the cash we need.
Trust me.
I've done this six times before,
I can certainly do it again."

"Larry's been doing this for years!" Lesley chimed in.

Telly glanced around the table.
The traveling salesman was hanging on Larry's every word.
George looked calm and not at all like he wanted to drop somebody into a toilet, which was practically raving approval coming from him.
The chairman was stroking his chin in thought, while all of the new members of the board looked like they were intrigued.

Whatever Larry was planning was going to carry the votes.
Now Telly had to both not get shot and avoid getting sent to jail with the rest of these people.
It was bound to be an even longer season.

== Chapter Two

Many believe that there are groups associated with or even fueled by powers fell and dark alike.
Many who hold this belief are certain that soccer supporters are deep in with such groups.
Some believed these powers to be of the devil.
Others, of ghosts.
Still others, of perhaps the old gods, the pagan deities.
But of course, we are not superstitious, so we know better.
Or so we think.

Arise, Hephaestus!
Come forth, oh craftsman of the volcanoes!
Bring forth your power for our ritual.
Alight into Detroit with your grim power, forge victory for our club, smite the remnant of the Alliance in our home!

The hivemind of goths completes their dread assembly, the mountain bursts forth, snug squarely between stadium and train tracks.
The coin for smoke is no more, but the smoke becomes ever more bountiful.
Northern beacon shine forth and smoke out all who face us.

The ball slots home, the stadium erupts with the clamor of crosstown dominance.
The grenadiers drop their offering of fish into Hephaestus's mount, bagging well the additional gift of a human unheeded.
Hephaestus responds with his gift, an eruption of smoke unlike any other seen in the game.
Billows rush down the east and over the pitch, covering every square meter in a fog of war Sun Tzu could not fight through.

"This is ridiculous," George grumbled.
"How is one to even sniff out the game through this?"

A joyous crowd takes no heed, continuing to sing and hurl abuse as the sun itself blots out.
White-clad opponents stumble and struggle to retain their footing.

"FUCK YOU! GET UP! YOU'RE NOT EVEN HURT! FUCK YOU FUCK YOU FUCK YOU!" come the screams.
What mooncalves stood against them!
Who would let something as small as crippling black smoke prevent them from running and playing at full speed with perfect situational awareness?
Certainly not their own players. 
No, only the opposition could be so senseless as to lose any capability in volcanic glee.

Again the ball is scored.
And again.
Every time, grim Hephaestus's handiwork replays again, to much the same scene.
Every time, George plots vengeance upon his tormentors.
The football match may be lost to the traitors who left the alliance, but George would see to their swift end after.

== Chapter Three

John looked at the expansion projection list, kneading his temple.
He was supposed to go on a podcast with 829 followers on Birdsite later this afternoon and discuss expansion, which would be a pivotal PR point before finalizing numbers with the league's sponsors to give a much-needed shot in the arm on revenue later.
The problem was that it was dubious whether _any_ new teams would be starting this year and taking them above the national minimum of 8 teams in the league.
What on earth was he supposed to even say under these circumstances?

A knock sounded at the door.
"Come in," John said.
Larry Garry entered the room and sat on the other side of his desk.
"I'm glad you're here," John said.
"I could really use some of that Harvard brain of yours on this problem."

Larry craned his head to take a look at the monitor.
"Not very many in the confirmed column, are there?" he asked, frowning.

"Not for this year," John said.
"We have plenty of groups looking to play two seasons from now, but next year is pivotal if we're going to get things back on track.
We need to build up a head of steam, and currently we're just always around the corner from that."

"Should be an easy fix," Larry said.
"I've got plenty of Silicon Valley experience in going fast and disrupting things.
All you have to do is present the facts a little bit differently."
Larry grabbed a rolodex labeled "expansion contacts" off of John's desk and flipped it open.
"Like look at this, you have... 16 total contacts?
Wait, you've been working on this for 2 years and you only have 16 names?"

"It's difficult to find people who will return my calls after the unpaid bill stories leaked out," John said defensively.
"Every single one of those is a good, active contact!"

"OK.
OK.
That's perfect, actually," Larry said.
"So you can tell them that you're in active conversations with 16 different markets and that they're very promising contacts."

"I said contacts, not markets," John said.
"And some of them haven't gone very deep- just a day of drinks and talking to them about the open system.
Some of them are partners or live in the same city."

Larry lit up.
"Well, a contact who you get drinks with is the only kind I really care about!
Anyway, just say they're all active market discussions.
We're an open system. 
In theory every single one of them could start up their own club or link up with somebody else to do it, right?
And every club is its own market.
It's not really a lie, it's just the most optimistic scenario possible, which is what everybody who still believes in the reality of 'independent soccer' wants to believe in anyway."

John pursed his lips and nodded.
"That could work.
It would be nice if we had more confirmed expansions in the meanwhile."

"Why is everyone waiting another year?" Larry asked.

"Cashflow issues or organizational readiness.
There's only so many people at these groups and it takes time to find a stadium, hire technical staff, make sure housing is worked out properly, and so on.
If you rushed some of them they might struggle to even make payroll on no amenities."

Larry leaned back and looked at the ceiling.
"You just need a little capital to make those sorts of problems go away," he mused.

"Which is what we're all short of," John said.
"It wouldn't hurt to get some of those expansion fees- sorry, mandatory share purchases- in a little sooner.
Heck, if we had more teams in I'd love to pocket some exit fees even more."

"That really is my favorite aspect of the system," Larry mused.
"You have to forfeit your shares if you leave and you pay more for that privilege than you paid to enter the league in the first place.
I think we might actually be the first company in the world to be making bank on what is technically a negative valuation.
I'm already dreaming up other applications for that."

"Focus," John said. 
"We need to make money now."

"Easy fix," Larry said. He leaned over again and punched in one of the numbers that was listed as joining the league two years from now.
"Ivan!
Hey, it's Larry calling on behalf of John.
Yeah, about next year- right, cash on hand- listen, the chairman and I were talking and he has your back.
Mhm.
Right, just like when they injected money into Snag Village when they ran out midseason- you get into any trouble that first year and he'll keep you afloat.
No, it's- what if we knocked off 20% of your expansion fee if you did it a year early, too?
Right, I meant the mandatory share purchase, there is never an expansion fee when you're inserted into ANAL.
OK! Great, it's a deal."
He hung up and turned back to John.

"You do a few more of those and you'll have your shot in the arm and that confirmed club count will be way up," he said with a grin.

The silence stretched out between the two of them before John finally spoke.
"Did you actually confirm with the chairman that he was good for that?
You know how badly his wife took him to the cleaners during that time period when we weren't paying the r-"

"Relax," Larry said.
"It literally doesn't matter whether they collapse mid-season and go out of business entirely.
All that matters is that they _start_ the season when we hand in the team sheet to the federation and while we talk to sponsors.
It's basically like check kiting, except the government would be fine with soccer dying entirely and so this is legal."

John bit his tongue.
It was stupid, and maybe it would kill the league, but by the time that happened he probably would have been fired by the chairman anyway.
Might as well roll with it while the money wasn't as bad as it could be.

John gave Larry a smile that didn't reach up to his eyes.
"Thanks, Larry," he said.
"If you could get out of here, I need to call into that podcast now."

Larry nodded and walked out.
As the phone rang, John noticed an old post-it note out of the corner of his eye.
_Find out exactly where Larry Gary is getting his money from._
Perhaps some question were better left unanswered.

== Chapter Four

The US Soccer Federation's disciplinary representative furrowed her brows at the footage that was being shown to her, idly running a finger along her pearl necklace.
"I understand your concern," she told George.
"Unfortuinately, there are no Cup rules against blotting out the sun via smoke called from a dark ritual invoking ancient Greek deities, even if the smoke did reach the field of play."

"It's ridiculous!" George fumed.
"They sabotaged the game.
How are we supposed to play through that kind of darkness?
They have been out to get me since I first had my favorite boy try out for them. You have to put an end to this!"

The representative inwardly sighed.
"Well, I suppose I could always call for a committee ruling on the spirit of- wait."
She leaned in and turned up the volume, listening closer to the feed.

"...NOT EVEN HURT! FUCK YOU FUCK YOU FUCK YOU!" came in louder on the replay.
The color drained from her face as she instinctively clutched at the necklace to give her hands something to do.

"Oh my," she said.

"Yes, the language-"

"I've simply never heard such a thing at a sporting event," the representative gasped, feeling fainter by the minute.
"This is simply terrible!"
The camera panned, showing a banner depicting a bear shitting in the woods.
"_Dear me_."
Whoever these Detroit people were, they weren't as bad as this George person was saying.
They were obviously far, far worse.
The last time she had seen an animal poop had been at the zoo, after which she had banned her children from returning for the sake of their own eyes.

George stared at the swooning woman as she crumpled over on her desk from the shock of the stimulation.
After taking a moment, he gently pushed her off the desk and sat at her computer as she hit the ground with a _thump_.
Access to the company directory... floor maps... everything he needed to go find somebody who could get something accomplished.
Liberating the representative's ID badge from her, he used it to activate the elevator and send him up towards the C-level suites.
He hadn't been able to get an appointment with the president of US soccer, but perhaps showing up unannounced could fix his woes.

== Chapter Five

Brian flipped his laptop end over end, exasperated.
"I've had it with these people!"

"What's the matter?" Larry asked, eyebrow raised at the miraculously unbroken machine.

"It's our marketing strategy," Brian said.

"I thought we didn't have any money left for marketing?"

"Right- it's all podcast interviews, a dozen Twitter accounts that I run, and editing Wikipedia to match our press releases," Brian explained.
"And that last part is the problem.
I'm arguing with this @CelticTiefling69 person who apparently edits half the pages for the Alliance and she's reverting all my edits!"

Larry nodded.
"What's even the point of a public resource like Wikipedia if we can't just make it a terse word vomit of all of our own messaging?
They're abusing the common good."

"EXACTLY!" Brian exclaimed. 
"I just can't reason with her anymore.
If I open another Wikipedia account then they'll ban me, and if I use any more of my Birdsite accounts to shout her down they'll figure out that I'm running all of them!"

_It might help if you hadn't included "Run by Brian" on half of them while making the exact same arguments on the other half,_ Larry mused.
Still, it was clear that letting this go wouldn't do.
If they couldn't salt Wikipedia, they might actually have to spend money on real marketing- and where was that going to come from?
He was already "forgetting" to ask ambulances to be available at his games so that it wouldn't cut into his top shelf liquor budget; there weren't many places left to cut costs.
Well, he'd just have to handle it himself.
Again.


----
BIRDSITE.IO
>> WELCOME BACK, NUTAVENUEKING <<
ENTER COMMAND > DIRECT MESSAGE
WHO? > CELTICTIEFLING69
ENTER YOUR MESSAGE BELOW...
----

@NutAvenueKing: Hey, I'd like to talk about what it would take to come to an understanding around our presence on Wikipedia.

@CelticTiefling69: Stop making edits from a hydra of sockpuppet accounts and stop citing your own PR statements.
You've all fallen through on so many promises that they're blacklisted as being acceptable as the sole source for a statement in an article.

Larry pursed his lips. 
It was true that the league had been _ambitious_ in their messaging in years past.
No arguing that one on its merits.
Maybe a bribe could work.
But how do you bribe the kind of nerd that would willingly deal with editing Wikipedia day to day?
_Information_.
Perfect.
He'd get on her good side with a few leaks.

@NutAvenueKing: You know... Flamingo Flight FC was going to be one of our first ANAL teams before the Alliance had its delayed launch.

@CelticTiefling69: Sure, OK.

@NutAvenueKing: In fact, they're working on coming back and joining us now.
They're very excited about what we're doing.

@CelticTiefling69: Why would anyone spend money to join a league that forgets to turn on the cameras for a stream at least every other week?
I don't believe you, and I don't care about any of this.
Leave.

@NutAvenueKing: Look, just tell me what you need in order for us to get more of our messaging out on Wikipedia.
We're just trying to help you with maintenance!

@CelticTiefling69: What I want is for you to stop treating it as a marketing arm and to go figure out how to fix your failing soccer business.
Leave me alone!
_Error Discontinuus_!

----
BIRDSITE.IO
DM WITH CELTICTIEFLING69 ENDED
YOU HAVE BEEN BLOCKED BY CELTICTIEFLING69
ENTER COMMAND > QUIT
----

_I wonder what that meant,_ Larry wondered.
His phone somehow felt chilly.


== Chapter Six

Cynthia Prism typed furiously at her computer, switching between windows and firing off emails in a hotkey-driven blur.
Every so often, somebody would misinterpret the current state of soccer in the United States as dozens of individually greedy stakeholders each trying to maximize profits in their own little fiefdoms.
But that couldn't be farther from the truth.
The reality was that a few elected officials in US Soccer controlled the entire thing, controlling the rise of empires and destroying grassroots movements with a few emails.
With just a few more days' work, she could finally close up the chapter on the recently deceased Promotion and Relegation Organization of Leagues, Academies and Players for Soccer Excellence.

Emails sent, she stood up and began to stretch.
Now if only she could wield the same level of power over the real enemy to her ambitions: professional cornhole.
It was hard work enforcing the bylaws and minimum standards to the letter, but somebody had to wield the rubber stamp.
As she finished working out the kinks in her back, the door opened- and in walked a vision.

The man walking into her office had the mustache of a powerful, sexy walrus.
His graying hair gave him the appearance of a distinguished, experienced man.
And the rest of his body- almost beyond description.
This wasn't a mere dad bod- that descriptor could never suffice for him.
No, the man before her had a _daddy_ bod.
Cynthia couldn't help herself- most powerful woman in the sport or not, she trembled a little with desire at first sight for who she estimated just might be the sexist man alive.

"My name is George, and I need to speak to you about a grave injustice," he said.

"Cynthia," she said.

George brought out his phone and once more brought up the video of the volcano smoking out the entire field, explaining to Cynthia what had occurred and all of the years of torment his sworn foes had put him through.
She barely listened to it all, stealing long glances at his body as he ranted and raved about one thing after another, only a few of which were really related to the matter at hand.
_Handshake agreement?_
_I could give you a good shake._

Finally she realized that he had stopped some time ago while her eyes were still wandering, and he was expecting a response.
She looked up and met him in the eyes.
"I can promise you that I'll fully correct the injustices I've seen," she said, voice edging into the sultry.
"We should definitely schedule a meeting so we can unify our interests."

"Yes!
I would like that very much.
We can finally squeeze the life out of these bloodsuckers."

_I'm certainly going to squeeze the life out of_ something _here_, she thought.

== Chapter Seven

_Some time ago_

Benjamin Quick sat on his knees before commissioner Donovan Grabber.
"So," the commissioner murmured, "you finally realized that working for your precious national team ultimately means working for me."

Ben cast his eyes downward.
A mere month ago, working with Grabber would have been unthinkable, equivalent to cavorting with the devil.
That was before Ted had broken up with him and made it clear that promotion and relegation was more important to him than their life together.
He took a deep breath, then lifted his eyes up to the commissioner.

"I'll do anything you ask, so long as you empower me to tkae my revenge," he said.
"I want to see Ted dead before me."

"His foolish ambitions were already a shambling husk," Grabber purred.

"No.
I want _him_ dead.
Not his dreams, not his ideals- him."

"Of course," Grabber said.
He was hardly above working with murderous psychos or taking their money.
Hell, a lot of them bought tickets.
"Stand.
In order for you to accomplish your goals, you're going to need power... significantly more power."

Grabber wordlessly led Quick to an elevator that took them all the way to the basement of the League's headquarters.
Deep within the bowels of the building, there was a machine with a man-sized glass tube.
Many power cables and hoses fed the monstrosity, whose function was opaque to the naked eye.
Grabber gestured for Ben to enter the tube.

"As everyone knows, leagues rise and die based on how mean people are on the Birdsite," Grabber noted.
"The Alliance will soon fall to the veritable flood of negative posts we send their way, and then the reform movement shall be crushed.
This Collector of Crap Kontent will-"

Ben suddenly collapsed from the force of the world's largest involuntary groan, the universe demanding counterbalance for contrivance.

"Ahem. 
It will collect all of the worst soccer-related content from the birdsite, convert it into gaseous form, and then flood the chamber with it.
You'll become a human embodiment of the worst of the scene, a potent weapon able to drive out the sanity of any who read your posts."

Ben picked himself up and stood up tall.
"Let's do this, then."

Grabber flipped a switch.
The machine connected up to Birdsite and began to pull down every post it could from reform-minded hashtags, from anti-reform accounts, and a few corporate accounts for good measure.
A loud humming filled the room as condensers rendered the posts into physical form, then superheated them up to eye-watering temperatures.
The gas began to flow in as Ben bit his tongue to avoid crying out in case it hurt.
Soon the entire room was obscured, with neither party able to see each other.

Improbably despite the temperature, the process didn't hurt at all.
Ben actually experienced it as a sort of cool breeze.
Finally, the gas cleared, and the tube opened up automatically.
"Gotta be honest, Don, I don't feel any different at all.
Nice way to cool off during the heat, at least."

Grabber frowned.
"Stay in there another minute please," he said.
The process was supposed to cause some level of mental and physical decay in exchange for granting power, but Quick seemed to not be affected at all.
Grabber checked the data inputs and shook his head.
Quick's own posts accounted for at least 20% of the data input.
That was never going to work.
What other data sources could he add in?

He pulled up the data sources tab.
Pro-monarchy Birdsite, that should be good.
Everyone who was still interacting with Joe Rogan online, for or against, probably had no filter.
It was still missing something.
He scrolled down until a single item stood out, simply labeled "GAMERS".
Without hesitation, he entered it into the input and immediately fired up the machine again.

This time, Ben's screaming was heard loud and clear through the smoke.
Plasma danced along the glass, the supercharged energy well beyond limits that would kill most people.
"STOP IT STOP IT PLEASE I BEG OF YOU!" Ben shrieked.
Grabber simply grinned.
He hadn't lifted his boot up to show mercy to any other fan who had come in begging him for assistance, and he certainly wouldn't start now.

Finally, the smoke cleared.
Ben's skin had turned a sickly green hue, a forked tongue flicking out nervously.
"Whaaaaat have you donnnne to meeeeeee?" he hissed.

"I have given you exactly what you asked for.
The power to destroy those in your path."

"I can feeeeel the sssstrength in my body," Ben said.
"I will killll Ted with thisssss powerrrr."

"That's all good and well," Donovan said.
"But I mostly need you to keep posting things on the Birdsite that will make the reform movement look stupid."

"I willll argueee your caseee."

"_Hell_ no.
I need you to keep arguing the reform side, much like how you have been, only moreso."

The forked tongue went in and out as Ben considered.
"Youuu do not waaant me to publicly ssssswitch?"

"Are you kidding?
You and Ted as a team were the third best thing that ever happened for us in terms of the movement looking stupid, and that's only because the Alliance and the Deltas exist to take the first two.
Now come on, we have a board meeting to get to."

* * *

_Months later..._

Ben stood triumphantly over the bodies of Noruhl and Easterly, then dialed out to the commissioner.
"Iiit isss finissshed," he rasped.
"The traitorsss are finaly finissshed."

"Good, Benjamin.
I knew I could count on you.
Now, listen.
We've finally located where one of our other old friends has left around a certain disk.
It could be a disaster if the wrong person got ahold of it- and right now the Alliance has the only copy."

Ben licked the air, taking in the aroma of his kill.
"Ssssurely you cannot mean- but he issss not even in the countryyyy."

"Correct.
He doesn't give a damn about the thing.
But rumor has it one of the other thorns in our side is attempting to sneak their way in and steal it."

Ben snarled.
"Theyyy will not even live to see this dissssk, let alone usssse it againsssst usss."


== Chapter Sex

George fumbled open the door to room 401 as Larry Gary had told him to.
"OK, I'm here buddy.
Now what did you want... to..."
George trailed off as he took in the sight before him. 
"What is all of this?"

The room was covered from top to bottom with pizzas.
Pizzas covered every square inch of floor.
The beds were loaded with pizzas.
Even the walls and ceiling were, improbably, laden with pizza- how they were staying on wasn't clear.
Not a single box was in sight.

And standing in the middle of it all was a stark naked Larry Gary, holding naught but the Coke that had clearly been influencing his behavior to this point.
"Shhhh," Larry said, his well-seasoned breadstick ready with the telltale firmness of one slightly too baked.
"We don't need any words.
All your previous betrayals were from mere handshake agreements.
But we can seal our working relationship with something far more meaningful."

"We really shouldn't," George said, sweating as Larry went for the buttons on his shirt.
_What would my wife say about this debauchery_, he wondered, but couldn't quite say aloud.
His wife didn't have the vision for business that he did. 
That's all this was: business, with a side of revenge.

As the shirt came off and his belt was loosened, George couldn't help himself but to feel Larry's breadstick.
It was buttery smooth, and just the right size- it would go into his mouth so smoothly.
George had gone for many a breadstick in his younger years- he knew perfection when it was in front of him.
It was surprisingly dark, all things considered.
Possibly the result of a little too much time in the heat.

Distracted, he hardly even realized that his shoes and pants had all been removed until Larry suddenly marched him over to the pizzas and shoved him onto them, sliding them across the cheese in one smooth motion before leaning into a deep kiss.
Before he could even properly think about how out of order that had been, George jumped as he realized that Larry had started to touch his prized pepperoni roll.
Larry might have a wide array of pizzas with all toppings around him, but George was a stout Balkan man and knew that the cure for the deepest craving that humanity had was a stout, powerful sausage.

Larry Gary began to stroke the sausage more intently.
"There's something... different about this," he murmured.
"It's not your typical... that is, it feels like it's already filled with-"

But in the meanwhile George had been transported back to his wilder younger days back in the old country.
Old times.
Old lovers.
In a moment he relived what had felt like an entire lifetime with a man who had proved to be another forbidden fruit- Colby Jack, who had seemingly always been semi-hard.

"Jack," George sighed, as if in a trance.

"Filled with jack?" Larry Gary asked, frowning.
That was no state to leave a pepperoni in.
Larry squeezed with furor.
It was time for a good jack off if he was going to get this sausage to the state he really wanted it to be in.
He worked it up and down, giving it a few licks.
All told, it was really quite delicious.
He let more of it into his mouth, showing off the capacity that had made him the class hot dog eating champion 5 years in a row in school.

Finally, the pepperoni surrendered its delightful filling, to the delight of both participants.
It wasn't easy to do so- only the alertness conferred by consuming large amounts of Coke made it possible.
Every time it seemed like there couldn't be any more, another spurt happened.
It was enough to make him wonder if he'd secretly worked through a calzone.

At long last the torrent of goo ended and Larry licked his lips, satisfied, as George gasped.
In 30 years of time with his wife, not once had she showed such aptitude at sausage handling as to leave it in such a state.
He opened his eyes and gazed at Larry Gary.
Both of them were simply covered in cheese now, but neither particularly cared. 
George allowed himself to roll over and settle into Larry's bought-and-paid-for sauce, marveling at what the juices did for his skin.

It wasn't long before Larry Gary decided that it was time for round two and for his breadstick to be handled.
With the wordless understanding that can only be expressed by two titans of business, Larry laid out a generous portion of oil onto George, then prepared for the difficult work of stuffing George's crust.
After all, why should his own stuffed cheesy bread be left in the lurch?
Filling transferral was no easy proposition, but Larry was a deft hand at pulling off doughy maneuvers.
And truth be told, once you had started in on them, you could hardly help but find it addictive to go for just one more- he was an adeptly practiced hand.

But even while ensuring a reciprocal unloading, Larry Gary couldn't help himself. 
While pumping his dispenser in and out to prepare for the crust stuffing, Larry gently stroked George's olives, dabbing the oil from them to his adjacent jalapeno.
He knew he had to be careful with this- it was possible to get too much heat- but he could barely help himself.
Finally, this all proved to be too much, and the crust was completely and utterly stuffed ahead of schedule.
There was a sense of timing to this, and he worried that he had simply loaded it up too quickly.
_I guess it's true what they say- nobody_ does _do it like the hut after all._
He rolled over to the other side of the king-sized bed, limbs flopping through pizzas as he went.

Tragically, and saving the author from the duty of writing some unconvincing aftercare, a nude Cynthia Prism finally made it up to the room, holding on firmly to an early-2000s handheld entertainment system.
"Looks like you boys started the dealmaking without me," she said, raising an eyebrow at the most catastrophic loss of a security deposit that had ever been made.

"That was not my fault," George gasped, panicking.
Larry Gary was not the only man that he needed a deeper-than-a-handshake agreement with- the man's impatience might have cost him the best chance he had at her all-important anchovies!
This was a disaster!

"Well, I suppose you boys could make it up to me," she said.
"You owe me a double battle."

Both Larry Gary and George were surprised to find that they were already prepared to link cables again and participate in a trademark-free entanglement. 
After the brief preparation of a load screen and the button tapping of some menuing, the men's onyx's were able to quickly use harden and tackle her cloister, hammering away until a string shot finale as they retracted.

George passed out face first into the pizzas.
He had simply no idea how he would explain this depravity to his wife later.
But at long last, he had something so much deeper than a handshake deal with the highest levels of US Soccer.
Revenge would be his soon.