= 1001 Football Crimes
Robert Mason
:doctype: book

== Chapter One

The annual meeting of the Autonomous National Alliance of Leagues was even more tense than usual, Kimberly Telly mused.
Perhaps it was the fact that their champion, Ted Easterly, had gone missing months ago.
Without his valiant posts at birdsite.io, the fortunes of the Alliance had collapsed almost immediately.
Apparently, hashtags really were the problem facing the movement- more than business fundamentals or network effects, the league had been sustained by generous souls willing to say #ProRelForUSA.
Once that had stopped, the clubs had begun to leave.

Of course, the fact that the chairman of the board was holding a gun to his head wasn't helping the mood much either. 
If he could just wait for everyone else at the table to collapse first, he could walk free.
He just had to survive until then.
Just had to _not_ get shot.

"Well... certainly, we've lost our primary marketing asset, one of our most reliable revenue sources, and any published media buzz," the chairman burbled.
"But the people must be on our side!
We've stuck true to our principles!"

Telly shook his head.
"The only people who are still following us are three podcasters who all live in Chattanooga."

"The ones who sent us hate mail every day that claim we're ruining their lives and destroying the movement entrusted to us?"

"Yes, them. It is nice to have somebody who cares, at least."

The room went quiet for a full minute.
Finally, the chairman cleared his throat.
"We could put out another book list-"

"What we need is money," Telly interjected.
"Almost nobody in this room has paid their bills."
"Everyone pays up today, we can clear out a lot of outstanding debts to hotels and liquor stores and referees or whoever else we've been stiffing and can move on and get the season going again smoothly.
Maybe we could even run an entire season where nobody commits any federal crimes!"

"Just so long as that doesn't include all of those graphic designers from the clubs the league ran?" the chairman asked.

"Sure, technically those clubs went bankrupt, and I'm still doing business with you, so we're well past the point of being concerned with petty moral obligations," Telly said glumly.

One man cleared his throat at the corner of the table.
"The soccer side of the business is not making money regardless of us paying our bills.
If we're going to get up to sustainability, we're going to have to start getting more creative."

"I agree with him!" another voice chimed in.

Telly groaned.
Larry Gary was a tech mogul in the worst sense of the term: disruptive and amoral, but without a billion dollars to show for it.
Every so often, he appeared to remember that he was running a soccer team- but those brief glimmers of lucidity were becoming fewer and farther between as the months ground on.
How exactly he had made a successful tech business was anyone's guess- Telly suspected that he had found it fruitful to simply pull investors off of the street, but was adamantly opposed to spending any of his precious time digging deeper into that fool's errand.

Worse still, Larry Gary's wife Lesley had recently left him.
Nobody could quite be sure why, but Larry had since taken to wearing a sockpuppet on his hand that he had named after her.
Legally speaking, the sockpuppet owned a second football team and had a vote in all board matters.
When Telly had attempted to challenge this, the chairman had vetoed it- contingent on a promise that the sockpuppet would never vote to oust him.

"What if we all simply ran good soccer clubs?" Telly asked.
"I've done it for ten years.
Practically pays for itself, almost, whenever we don't get bored and call up La Liga sides to see if they want to hang out in the US.
Maybe we could even have an entire season where nobody commits any federal crimes!
What do you all say?"

"Not nearly enough money for as quickly as we need capital," Larry said.
"We're going to have to get really creative if we're going to move the cash we need.
Trust me.
I've done this six times before,
I can certainly do it again."

"Larry's been doing this for years!" Lesley chimed in.

Telly glanced around the table.
The traveling salesman was hanging on Larry's every word.
George looked calm and not at all like he wanted to drop somebody into a toilet, which was practically raving approval coming from him.
The chairman was stroking his chin in thought, while all of the new members of the board looked like they were intrigued.

Whatever Larry was planning was going to carry the votes.
Now Telly had to both not get shot and avoid getting sent to jail with the rest of these people.
It was bound to be an even longer season.


== Chapter Sex

George fumbled open the door to room 401 as Larry Gary had told him to.
"OK, I'm here buddy.
Now what did you want... to..."
George trailed off as he took in the sight before him. 
"What is all of this?"

The room was covered from top to bottom with pizzas.
Pizzas covered every square inch of floor.
The beds were loaded with pizzas.
Even the walls and ceiling were, improbably, laden with pizza- how they were staying on wasn't clear.
Not a single box was in sight.

And standing in the middle of it all was a stark naked Larry Gary, holding naught but the Coke that had clearly been influencing his behavior to this point.
"Shhhh," Larry said, his well-seasoned breadstick ready with the telltale firmness of one slightly too baked.
"We don't need any words.
All your previous betrayals were from mere handshake agreements.
But we can seal our working relationship with something far more meaningful."

"We really shouldn't," George said, sweating as Larry went for the buttons on his shirt.
_What would my wife say about this debauchery_, he wondered, but couldn't quite say aloud.
His wife didn't have the vision for business that he did. 
That's all this was: business, with a side of revenge.

As the shirt came off and his belt was loosened, George couldn't help himself but to feel Larry's breadstick.
It was buttery smooth, and just the right size- it would go into his mouth so smoothly.
George had gone for many a breadstick in his younger years- he knew perfection when it was in front of him.
It was surprisingly dark, all things considered.
Possibly the result of a little too much time in the heat.

Distracted, he hardly even realized that his shoes and pants had all been removed until Larry suddenly marched him over to the pizzas and shoved him onto them, sliding them across the cheese in one smooth motion before leaning into a deep kiss.
Before he could even properly think about how out of order that had been, George jumped as he realized that Larry had started to touch his prized pepperoni roll.
Larry might have a wide array of pizzas with all toppings around him, but George was a stout Balkan man and knew that the cure for the deepest craving that humanity had was a stout, powerful sausage.

Larry Gary began to stroke the sausage more intently.
"There's something... different about this," he murmured.
"It's not your typical... that is, it feels like it's already filled with-"

But in the meanwhile George had been transported back to his wilder younger days back in the old country.
Old times.
Old lovers.
In a moment he relived what had felt like an entire lifetime with a man who had proved to be another forbidden fruit- Colby Jack, who had seemingly always been semi-hard.

"Jack," George sighed, as if in a trance.

"Filled with jack?" Larry Gary asked, frowning.
That was no state to leave a pepperoni in.
Larry squeezed with furor.
It was time for a good jack off if he was going to get this sausage to the state he really wanted it to be in.
He worked it up and down, giving it a few licks.
All told, it was really quite delicious.
He let more of it into his mouth, showing off the capacity that had made him the class hot dog eating champion 5 years in a row in school.

Finally, the pepperoni surrendered its delightful filling, to the delight of both participants.
It wasn't easy to do so- only the alertness conferred by consuming large amounts of Coke made it possible.
Every time it seemed like there couldn't be any more, another spurt happened.
It was enough to make him wonder if he'd secretly worked through a calzone.

At long last the torrent of goo ended and Larry licked his lips, satisfied, as George gasped.
In 30 years of time with his wife, not once had she showed such aptitude at sausage handling as to leave it in such a state.
He opened his eyes and gazed at Larry Gary.
Both of them were simply covered in cheese now, but neither particularly cared. 
George allowed himself to roll over and settle into Larry's bought-and-paid-for sauce, marveling at what the juices did for his skin.

It wasn't long before Larry Gary decided that it was time for round two and for his breadstick to be handled.
With the wordless understanding that can only be expressed by two titans of business, Larry laid out a generous portion of oil onto George, then prepared for the difficult work of stuffing George's crust.
After all, why should his own stuffed cheesy bread be left in the lurch?
Filling transferral was no easy proposition, but Larry was a deft hand at pulling off doughy maneuvers.
And truth be told, once you had started in on them, you could hardly help but find it addictive to go for just one more- he was an adeptly practiced hand.

But even while ensuring a reciprocal unloading, Larry Gary couldn't help himself. 
While pumping his dispenser in and out to prepare for the crust stuffing, Larry gently stroked George's olives, dabbing the oil from them to his adjacent jalapeno.
He knew he had to be careful with this- it was possible to get too much heat- but he could barely help himself.
Finally, this all proved to be too much, and the crust was completely and utterly stuffed ahead of schedule.
There was a sense of timing to this, and he worried that he had simply loaded it up too quickly.
_I guess it's true what they say- nobody_ does _do it like the hut after all._
He rolled over to the other side of the king-sized bed, limbs flopping through pizzas as he went.

Tragically, and saving the author from the duty of writing some unconvincing aftercare, a nude Cynthia Prism finally made it up to the room, holding on firmly to an early-2000s handheld entertainment system.
"Looks like you boys started the dealmaking without me," she said, raising an eyebrow at the most catastrophic loss of a security deposit that had ever been made.

"That was not my fault," George gasped, panicking.
Larry Gary was not the only man that he needed a deeper-than-a-handshake agreement with- the man's impatience might have cost him the best chance he had at her all-important anchovies!
This was a disaster!

"Well, I suppose you boys could make it up to me," she said.
"You owe me a double battle."

Both Larry Gary and George were surprised to find that they were already prepared to link cables again and participate in a trademark-free entanglement. 
After the brief preparation of a load screen and the button tapping of some menuing, the men's onyx's were able to quickly use harden and tackle her cloister, hammering away until a string shot finale as they retracted.

George passed out face first into the pizzas.
He had simply no idea how he would explain this depravity to his wife later.
But at long last, he had something so much deeper than a handshake deal with the highest levels of US Soccer.
Revenge would be his soon.