= Relegated Love
Taco
v0.0, 2021-06
:doctype: book

== Chapter One

The most powerful men in United States soccer met on a chilly February evening, gathered around a table with a holographic projector.
The group was often accused of being an old boys' club, but that was hardly fair- some of these men were relatively young, after all.
As the droll details of the group's finances were run through, they churned through an impressive spread of McDonald's.
It was generally allocated across the entire group, with classics like the Whopper (TM) alongside new items like the Spicy Chicken Nuggets with Mighty Hot Sauce (TM), with gallons of Diet Coke to go around.

Finally the charts wrapped up- the project's ability to display 3D imagery correctly to all viewing angles was a technological marvel, but perhaps wasted on showing spreadsheets to disinterested stakeholders.
Commissioner Donovan Grabber cleared his throat.
"Gentleman," he said, "It is now time to turn to the real order of business today."
With a click of a button, the projector flipped to a map of the United States with each of their major franchises highlighted in blue, demonstrating their command of the market.
"For some time now, our dominance has been virtually unchallenged.
Whatever we want from a market, we take.
Sometimes our marketing crews simply take from a market entirely.
But as of last night... we are under threat."

With another click of the button, a series of red dots appeared in the hologram.
"These are the new teams of the newly formed Autonomous National Alliance of Leagues. 
A would-be resistance movement that believes they can upend the rules of our system and institute a system of promotion and relegation.
It is antithetical to everything we have done to Hashtag Grow The Game (TM) and exercise our complete control over the system."

"Promotion and relegation in the United States," hissed a hooded figure from one end of the table, "would be the most seismic event in world hisssstory.
It would change the entire world overnight."

"Correct," Grabber said. 
"Our entire mission in a way that preseves the geopolitical status quo.
If the Alliance succeeds, it is impossible to tell what the consequences would be for nation states around the world."

"Sssssporting dominance," the hooded figure hissed further.
"Buy-in with the national teaaam."

"Are you quite done?" Grabber asked.

"Latinoooos," the figure hissed.

"What threat could they possibly pose?" asked one of the owners around the table.
"Let's just simply use our normal playbook- buy a few teams here, fauxmote a team there, and use rumors to hinder the momentum of the rest."

"I'm afraid the situation is advancing quickly," Grabber said.
"Several teams in the league have already begun using Hashtag Pro Rel For USA banners."

Several gasps and murmurs went around the table.
A lower-league team that refused to say Hashtag Pro Rel For USA was doomed from the start, as had been proven through decades of experience.
Every single one that didn't do it had folded.
But it was a slowly spreading secret that by simply using the words, a team could protect itself from all manner of market calamities.
It was modern-day magic distilled into banner form- market fundamentals and revenues would take a backseat to using the correct memetic invocations.

"All they need to do is get 60 owners who are willing to take repeated losses in unpredictable market conditions, and I'm afraid they'll be able to institute an internal pyramid to counter ours.
From there it's simply a hop skip and a jump to overturning our closed system and enforcing open access, unleashing the most devastating tides of history.
Regimes would change.
Wars could begin overnight- or even end.
And we are the only ones who can stop it," Grabber said, taking a long draw from his Diet Coke straw until it began to make that open air suckling noise.
He swished the straw around a little to get what was left at the bottom of the cup, finally admitting that he would need to go refill it as he popped off the top.

"What do we have to counteract this?" another owner asked.

"Unfortunately not much," Grabber lamented as he feathered the Coke button, trying to get as much into the cup as possible while letting the fizz die down.
"Billions of dollars of pooled assets.
Almost exclusive media access in dozens of markets.
FIFA officials who are overwhelmingly in our favor due to their tendency to find unmarked bags of cash after trips to Brazilian steakhouses.
Case law precedent ruling in our favor despite explicit rules stating otherwise."

"Asssssassssssinnssssssss," the hooded figure hissed.

"The New York double agents are no longer able to take to the field," Grabber corrected.

"It's hopeless!" one owner wailed.
"They have us flanked on every front!"

"We could rebrand!" chimed in another.

"Shuffle some teams around," someone said, clutching a pair of 40-sided dice.

This continued for several minutes, with Commissioner Grabber desperately attempting to call order to the situation with his dozens of bosses.
Finally, one man stood up.
"Boys, I do believe this is where I come in," he beamed proudly.

A hush fell around the rest of the room.
Alexi Noruhl, the hero of many a social media campaign, was one of the few who could command enough respect in this group of people to take charge.
"It's true that their business model allows them to create new teams even more quickly than they dissolve," Alexi said.
"They have a bunch of hastily screen-printed banners that distort our ability to use blunt-force market trauma to win a game of Ayn Rand's Battlespreadsheets against them.
But do they have a former World Cup player who is willing to use misleading formulations about mouse traps on Twitter?"

The murmuring returned, but this time it had a positive sound to it as people saw hope.
"Do they have anyone who can look at a simple formulation that has worked around the globe, and instead suggest an overly complicated alternative that has never happened anywhere?"

"Speak on, Alexi!" shouted one man, a series of hands beating on the table in support.

"Do they have the budget to have someone sit on the web all day and make disingenuous arguments!" Noruhl practically shouted, drunk on the momentum.

"They do have fans who pretend to work in offices- oof!" one dissenter suggested, shortly before being elbowed and shushed.

"Worry not," Noruhl said soothingly. 
"As underresourced as we are- as big of a threat to the game as this is- I will not allow them to ruin our system.
I will strike them where it hurts," he paused.
The room shook with collective anticipation, held near the edge.

"I'm going to tweet them into thinking they don't even want it," Noruhl finished with a grin.
The energy in the room reached its climax, a thunderous applause as dozens of fleshy hands noisily expressed their ecstasy for their red-maned savior.
If this new Alliance thought it would be easy to overcome a room of scrappy billionaires, they were sorely mistaken.

== Chapter Two

_Seven months ago_

The waves lapped onto the shore of the private beach, pulling the mind into a peaceful repose.
Seagulls could be heard overhead, far enough for their cries to be enjoyed without being so close that they were a threat to any of the food here.
It was idyllic.
Transcendent.
Benjamin Quick's head was nestled on the chest of Thaddeus "Ted" Easterly, and he was sure he had never been so happy in his life.

After the past three years together, they had taken this retreat together.
Sure, it had been enjoyable distributing so many banners and running the last true resistance against the forces of US Soccer.
But there were limits to how much joy one could get from building a presence as an influencer on the dime of a cosmopolitan billionaire.
This weekend would be the moment where Ben's life would change forever.

He'd been half-dozing off, but at the thought he suddenly felt his pulse quicken.
It took an effort not to spasm.
He craned his head up and looked at Ted.
The timing wasn't "right", but hell- when had he ever worried about timing in his life?
Moderation was for others- in this moment, he felt he had to move forward.

He fumbled into the pockets of his shorts and grabbed a small box.
"Babe," he said, tracing his finger along Ted's chest.

"Mmmm?" Ted murmured, breathing a little more deeply.

"I need to ask you something," Ben said, struggling to get the words out smoothly as he moved off of Ted's chest.

"What is it?" Ted asked, getting up and stretching.

Ben went down to one knee and opened the ring box. 
"Hon, I... will you marry me?"

Ted went silent for a moment, eyes bulging. 
"I..."

Ben bit his lip, eyes misting a little. 
He was a little scared, but he knew that after all their time together, after all the hashtags they'd built, that the answer could never be in doubt.
"I love you," he said.

"I... are you out of your mind?!" Ted yelled, practically spitting.

"What?!"

"You want to go _single-entity_ with me?" Ted continued, stomping furiously.

Ben's jaw dropped.
"Hon, this isn't-"

"All of this time we've spent building an _open system_ where poor performance was harshly dealt with.
It's the one constant of my life, Ben.
I don't tolerate closed systems for my soccer.
I don't tolerate closed systems for my government.
And I don't tolerate closed systems in my relationships!"

"But... we said we're always committed to-"

"To our partnership and the best ideas," Ted reprimanded.
"If there could be a better idea in all things than the principle of promotion and relegation, then I would promote it to my first priority.
But there isn't.
You just betrayed the one constant, Ben.
It's over." Ted stomped off towards the cabin.

Ben panicked and chased after him.
"Wait- of course I made a mistake here.
We can patch this up.
We can continue the way it was!"

"You tried to breakaway from our system.
I'm points deducting you and relegating you back out of my life."
Ted finished packing and zipped up his suitcase, heading for the door. When he got there, he turned.
"In a year or three though... I could see you promoting your way back into my top flight, though."

Ted walked out the door, leaving Ben agape. _What just happened?_