= Relegated Love
Taco
:doctype: book

== Chapter One

The most powerful men in United States soccer met on a chilly February evening, gathered around a table with a holographic projector.
The group was often accused of being an old boys' club, but that was hardly fair- some of these men were relatively young, after all.
As the droll details of the group's finances were run through, they churned through an impressive spread of McDonald's.
It was generally allocated across the entire group, with classics like the Whopper (TM) alongside new items like the Spicy Chicken Nuggets with Mighty Hot Sauce (TM), with gallons of Diet Coke to go around.

Finally the charts wrapped up- the project's ability to display 3D imagery correctly to all viewing angles was a technological marvel, but perhaps wasted on showing spreadsheets to disinterested stakeholders.
Commissioner Donovan Grabber cleared his throat.
"Gentleman," he said, "It is now time to turn to the real order of business today."
With a click of a button, the projector flipped to a map of the United States with each of their major franchises highlighted in blue, demonstrating their command of the market.
"For some time now, our dominance has been virtually unchallenged.
Whatever we want from a market, we take.
Sometimes our marketing crews simply take from a market entirely.
But as of last night... we are under threat."

With another click of the button, a series of red dots appeared in the hologram.
"These are the new teams of the newly formed Autonomous National Alliance of Leagues. 
A would-be resistance movement that believes they can upend the rules of our system and institute a system of promotion and relegation.
It is antithetical to everything we have done to Hashtag Grow The Game (TM) and exercise our complete control over the system."

"Promotion and relegation in the United Statesssss," hissed a hooded figure from one end of the table, "would be the most seismic event in world hisssstory.
It would change the entire world overnight."

"Correct," Grabber said. 
"Our entire mission in a way that preseves the geopolitical status quo.
If the Alliance succeeds, it is impossible to tell what the consequences would be for nation states around the world."

"Sssssporting dominance," the hooded figure hissed further.
"Buy-in with the national teaaam."

"Are you quite done?" Grabber asked.

"Latinoooos," the figure hissed.

"What threat could they possibly pose?" asked one of the owners around the table.
"Let's just simply use our normal playbook- buy a few teams here, fauxmote a team there, and use rumors to hinder the momentum of the rest."

"I'm afraid the situation is advancing quickly," Grabber said.
"Several teams in the league have already begun using Hashtag Pro Rel For USA banners."

Several gasps and murmurs went around the table.
A lower-league team that refused to say Hashtag Pro Rel For USA was doomed from the start, as had been proven through decades of experience.
Every single one that didn't do it had folded.
But it was a slowly spreading secret that by simply using the words, a team could protect itself from all manner of market calamities.
It was modern-day magic distilled into banner form- market fundamentals and revenues would take a backseat to using the correct memetic invocations.

"All they need to do is get 60 owners who are willing to take repeated losses in unpredictable market conditions, and I'm afraid they'll be able to institute an internal pyramid to counter ours.
From there it's simply a hop skip and a jump to overturning our closed system and enforcing open access, unleashing the most devastating tides of history.
Regimes would change.
Wars could begin overnight- or even end.
And we are the only ones who can stop it," Grabber said, taking a long draw from his Diet Coke straw until it began to make that open air suckling noise.
He swished the straw around a little to get what was left at the bottom of the cup, finally admitting that he would need to go refill it as he popped off the top.

"What do we have to counteract this?" another owner asked.

"Unfortunately not much," Grabber lamented as he feathered the Coke button, trying to get as much into the cup as possible while letting the fizz die down.
"Billions of dollars of pooled assets.
Almost exclusive media access in dozens of markets.
FIFA officials who are overwhelmingly in our favor due to their tendency to find unmarked bags of cash after trips to Brazilian steakhouses.
Case law precedent ruling in our favor despite explicit rules stating otherwise."

"Asssssassssssinnssssssss," the hooded figure hissed.

"The New York double agents are no longer able to take to the field," Grabber corrected.

"It's hopeless!" one owner wailed.
"They have us flanked on every front!"

"We could rebrand!" chimed in another.

"Shuffle some teams around," someone said, clutching a pair of 40-sided dice.

This continued for several minutes, with Commissioner Grabber desperately attempting to call order to the situation with his dozens of bosses.
Finally, one man stood up.
"Boys, I do believe this is where I come in," he beamed proudly.

A hush fell around the rest of the room.
Alexi Noruhl, the hero of many a social media campaign, was one of the few who could command enough respect in this group of people to take charge.
"It's true that their business model allows them to create new teams even more quickly than they dissolve," Alexi said.
"They have a bunch of hastily screen-printed banners that distort our ability to use blunt-force market trauma to win a game of Ayn Rand's Battlespreadsheets against them.
But do they have a former World Cup player who is willing to use misleading formulations about mouse traps on Twitter?"

The murmuring returned, but this time it had a positive sound to it as people saw hope.
"Do they have anyone who can look at a simple formulation that has worked around the globe, and instead suggest an overly complicated alternative that has never happened anywhere?"

"Speak on, Alexi!" shouted one man, a series of hands beating on the table in support.

"Do they have the budget to have someone sit on the web all day and make disingenuous arguments!" Noruhl practically shouted, drunk on the momentum.

"They do have fans who pretend to work in offices- oof!" one dissenter suggested, shortly before being elbowed and shushed.

"Worry not," Noruhl said soothingly. 
"As underresourced as we are- as big of a threat to the game as this is- I will not allow them to ruin our system.
I will strike them where it hurts," he paused.
The room shook with collective anticipation, held near the edge.

"I'm going to tweet them into thinking they don't even want it," Noruhl finished with a grin.
The energy in the room reached its climax, a thunderous applause as dozens of fleshy hands noisily expressed their ecstasy for their red-maned savior.
If this new Alliance thought it would be easy to overcome a room of scrappy billionaires, they were sorely mistaken.

== Chapter Two

_Seven months ago_

The waves lapped onto the shore of the private beach, pulling the mind into a peaceful repose.
Seagulls could be heard overhead, far enough for their cries to be enjoyed without being so close that they were a threat to any of the food here.
It was idyllic.
Transcendent.
Benjamin Quick's head was nestled on the chest of Thaddeus "Ted" Easterly, and he was sure he had never been so happy in his life.

After the past three years together, they had taken this retreat together.
Sure, it had been enjoyable distributing so many banners and running the last true resistance against the forces of US Soccer.
But there were limits to how much joy one could get from building a presence as an influencer on the dime of a cosmopolitan billionaire.
This weekend would be the moment where Ben's life would change forever.

He'd been half-dozing off, but at the thought he suddenly felt his pulse quicken.
It took an effort not to spasm.
He craned his head up and looked at Ted.
The timing wasn't "right", but hell- when had he ever worried about timing in his life?
Moderation was for others- in this moment, he felt he had to move forward.

He fumbled into the pockets of his shorts and grabbed a small box.
"Babe," he said, tracing his finger along Ted's chest.

"Mmmm?" Ted murmured, breathing a little more deeply.

"I need to ask you something," Ben said, struggling to get the words out smoothly as he moved off of Ted's chest.

"What is it?" Ted asked, getting up and stretching.

Ben went down to one knee and opened the ring box. 
"Hon, I... will you marry me?"

Ted went silent for a moment, eyes bulging. 
"I..."

Ben bit his lip, eyes misting a little. 
He was a little scared, but he knew that after all their time together, after all the hashtags they'd built, that the answer could never be in doubt.
"I love you," he said.

"I... are you out of your mind?!" Ted yelled, practically spitting.

"What?!"

"You want to go _single-entity_ with me?" Ted continued, stomping furiously.

Ben's jaw dropped.
"Hon, this isn't-"

"All of this time we've spent building an _open system_ where poor performance was harshly dealt with.
It's the one constant of my life, Ben.
I don't tolerate closed systems for my soccer.
I don't tolerate closed systems for my government.
And I don't tolerate closed systems in my relationships!"

"But... we said we're always committed to-"

"To our partnership and the best ideas," Ted reprimanded.
"If there could be a better idea in all things than the principle of promotion and relegation, then I would promote it to my first priority.
But there isn't.
You just betrayed the one constant, Ben.
It's over." Ted stomped off towards the cabin.

Ben panicked and chased after him.
"Wait- of course I made a mistake here.
We can patch this up.
We can continue the way it was!"

"You tried to breakaway from our system.
I'm points deducting you and relegating you back out of my life."
Ted finished packing and zipped up his suitcase, heading for the door. When he got there, he turned.
"In a year or three though... I could see you promoting your way back into my top flight, though."

Ted walked out the door, leaving Ben agape. _What just happened?_

== Chapter Three

_The present, or whatever time this is set in anyway, look, the point is that this is seven months after that previous chapter_

Alexi Noruhl took his laptop to his local Buffalo Wild Wings, set to begin his war against the A.N.A.L.
After finishing his meal, he took out the laptop and set it up at the bar, nursing another pint as he worked.
He plugged in the USB security key that would automatically connect his laptop on a secure tunnel back to US Soccer's internal networks, then navigated to birdsite.io.
He began a new thread, and began to work the magic that US Soccer's Special Projects Division paid him so highly for.
Some people said it was nonsense, but what they failed to understand was that as long as the check cleared, anything could make sense.

----
BIRDSITE.IO
ENTER COMMAND > NEW
----
A lot of people here are saying that they're excited for ANAL and for the possibilities that ANAL has for all of US Soccer. These people think that all of our other leagues should be forced into promotion and relegation, possibly against their will.

But this is wrong. This is America. Sure, pro/rel is a great principle, but why should anyone be forced into it against their will? We've built our own system here and it's working great for some folks.

When they built it, all they did was agree with FIFA that in exchange for hosting the world cup in the US, that a first-division league with promotion and relegation would be established. But they never said when it would be ready by, or which owners would assemble it.

So now ANAL is coming to do this. Great! This is their opportunity to build a better mousetrap. We could always just do two things. Some people would say that this is wrong, that it's overcomplicated, that we only need one system.

But if that was true, why do kids love Rube Goldberg so much? I used to see Rube Goldberg machines in Tom and Jerry cartoons growing up and they were classic. I truly think the best way you could grow the game in this country is to make the Rube Goldberg of divisional structures.

This new thing with promotion and relegation can have its own championships and interact using the US Open Cup, and everything can operate on their own separate schedules and rules and occasionally barely interact.

The result will be a finely tuned machine where figuring out how it works will be just as interesting as what the machine produces. If you've ever watched How It's Made, that's a winning formula. And that's what I'm proposing we build here.

I don't want anyone to be forced to do something they wouldn't like. I wouldn't want to be forced to get rid of my mousetraps, and then go to the store, and buy even more mousetraps, just because you like your new model better!

Especially not after all of the peanut butter I just applied to these ones. We have to take care of these investors- if we were to send them down a division, it would be the equivalent of lighting some of their mousetraps on fire, which could light their house on fire.

And frankly, with the kind of cheap construction materials we've been using, the US Soccer neighborhood could go up in smoke at that point.

Protect America.
Protect Soccer.

Leave our mousetraps alone.

----
BIRDSITE.IO
ENTER COMMAND > PUBLISH
PUBLISHING...
PUBLICATION COMPLETE. 
WOULD YOU LIKE TO EDIT? > NO
ENTER COMMAND > QUIT
----

Alexi nodded, satisfied, then unplugged the security key and set it down for a moment as he began to pack up his laptop.

"This is ridiculous," the man next to him said.
"Why would I ever watch this crap soccer on the TV when there's no connection with the lower leagues?"

Something within Alexi stirred.
Business meetings around TV ratings and how to increase them came back to his mind.
This could be a potential customer.
He had a rare opportunity to do some in-person market research.
He turned his head to look at who spoke, then came up short.

The man next to him was a relatively average-looking white male.
The beginnings of a 5 o'clock shadow on his face.
Standard haircut stuffed underneath a ballcap with no team or logo on it.
In other words, breathtaking.
Alexi struggled to remember what he was going to say.

"You see it, right?" the man next to him asked.
"If this top league is just its own thing but isn't _directly_ connected with everything below, there's just not nearly as many compelling stories.
But you connect it all up- probably 10 times as many people would have a reason to watch that championship. Maybe 100."

The words produced a chaos of emotion within Alexi. 
They sounded wrong, and yet for all that, he could feel an explosion of new ideas bubbling up within him.

"Yes... I think, I think you might be right," Noruhl said.
Noticing his conversation partner's empty glass, he flagged down the bartender.
"Can I buy you another round?" he asked.

"By all means. Name's Ted." They shook hands.

"Alexi. Glad to meet you, Ted. I'm looking forward to some great intercourse with you."
He choked.
"Er, discouse."

Ted lifted a single eyebrow, taking a sip from his new pint.

== Chapter Four

The evening passed by in a blur- little moments here and there, all of it inevitable foreshadowing for drafting up the evening of their life.
They went back together to Alexi's hotel room and kissed as his body made the targeted blood allocation of his life.
The long months spent on the road had resulted in a surplus in his testosterone budget, but he was ready to make the budget charge of his life with his homegrown players.
They eagerly tore at each others' clothes, Alexi hungrier than ever to fill Ted's supplemental roster slot with his designated player in defiance of league rules against fraternizing with the enemy.

With the eagerness of an author who doesn't know what they're doing but is desperately seeking to finish as quickly as possible, Alexi finished stripping Ted and flipped him over, lubricating himself to prepare for an impending transfer.
Poised above the flesh maw of unification, his flesh submersible plunged into the abyss, questing for its chance to make a header straight into Ted's orgasm button.
"N-n-nice ball control" Ted panted between moans.
Alexi could see it now.
Relegating this man below him- it promoted his senses to such heights he couldn't believe he'd never sought this out before.
He bounced, using his fingers to caress out a touchline as he let out a moan of his own, his own attack pressing onwards.

It had been years since he had gone the full 90 as a young man, and Alexi knew instinctively that it wouldn't happen today, either.
He slotted home his goal, a 1-0 performance that cemented victory.
Alexi rolled off and they stared at each other, gasping.
This man- this amazing man- Ted was his match of a man. 
There could be no doubt about that.
They laid there together and cuddled through the evening.
Tomorrow, Alexi would call his bosses and report the other thing he had picked up this evening: the way to defeat the Alliance.

== Chapter Five

"And so," the holographic image of Noruhl said, "he gave me the insight we need to defeat ANAL."

Commissioner Grabber visibly choked on his Diet Coke. 
"I didn't need to know that much about your evening."

"Sorry, I meant the Alliance. 
All we need to do is form our own lower division, directly connected to the first one.
Once we have that, we can strangle them from both directions. 
They won't have a leg to stand on- we can own the entire system.
Our mistake thus far had been in assuming that simply controlling the top will let us control everything."

Grabber shook his head.
"We already have our partnership with-"

"Our _own_ league", Noruhl interrupted.
"Everything within our own system.
No more allowing people to manage other chunks of it when we can extract every dollar."

Grabber considered.
"It could work.
It could absolutely work.
It would certainly put them in a weaker position."
He chewed on the straw for his Diet Coke.
"That doesn't kill the Alliance in and of itself, though.
We need to pull out their lynchpin."

"I've been tweeting for years saying how much I love them and had bought in-"

"All of the residual hate you gain on Birdsite isn't going to transfer enough to make them collapse," Grabber groused.
"We need something a bit more direct."
He stabbed the End Call button and drummed his fingers on the table for a minute, then finally paged his secretary.
"Get the owner of LP White Dwarves on the line."

A moment later, the mustachioed owner of the most infamous team of the Alliance appeared.

"I understand you're trying to leave after all of the injustices visited on you," Grabber said.
"I believe I can offer you very, very agreeable terms..."

== Chapter Six

"I don't understand," you say from your seat in the clubhouse.
"You found what again?"

"It's a security key," the needlessly shirtless hacker in front of you says, a hint of glisten on their pecs.
"Found it at the bar at a Buffalo Wild Wings."

"You're still eating there?" someone else at the table asks.
"The food at that place is saltier than a Chattanooga podcaster."

"Only when it's required to make a plot work. 
That's not important, though. 
What is important is what's on this sucker."
They fidget with the drive in their fingers, clearly overexcited.
"It's a remote access key for US Soccer.
You plug this into a PC and you're past every firewall that org has- dropped straight into the corporate intranet.
I poked around with it earlier- you can see damn near anything."
A devilish glint was showing in their eyes.
At least you think it is.
That might just be how they look all the time.

"So... what are you going to do with it?" you ask.

This time there's no mistaking it.
The grin you get in response is feral.

"We're going to go fill this clubhouse _with crime_."

== Chapter Seven

In the US Soccer Network Security Operations Center, lights began to flash from green to red like an overwrought Christmas tree on display at Bronner's.
"What's going on?" the incident commander asked, scrutinizing the network topology graph.

"Ransomware worm," one of the analysts said, typing furiously and in clear distress.

"Origin?"

"Still working on that," the analyst said, a stream of hexadecimal characters scrolling furiously down her monitor.
"Memory dumps don't appear to match any new messages in any inboxes.
There's nothing in the SIEM indicating an attack on the perimeter.
It's almost as if this problem originated on the inside to begin with."

The incident commander nodded.
"What operational abilities are impacted?"

"20% of end-user machines have already been encrypted, but for the most part all of the work was either backed up or it helps us to have accidentally lost it given the ongoing hydra lawsuit," the analyst said.
"Holotank phone banks are all down.
And it appears that payment processor #5 is unable to use its outbound modem for some reason."

"Which one is processor #5?" the commander asked. "Those are all mainframes that are running code that dates back before the first NASL, aren't they?"

"That's 1-4, sir.
#5 is the latter-day special projects system that's used for information operations. Think cassette tapes instead of punchcard decks."

The commander froze.
She knew #5 was bad news.
"Isolate the affected network segments immediately. 
Bringing processor #5 back up is your immediate priority.
Get in touch with the hacker if you can and pay the ransom on that.
We only have four hours until the weekly batch run on that processor and if it doesn't go, it can't run again until the week after."

The commander sprinted out of the SOC into her office, closed the door, and dialed Commissioner Grabber.
"We have a problem," she said.

== Chapter Eight

"What the hell do you mean you don't want anything?" Grabber typed the message angrily into the message window with one "DaddyTaco", who had allegedly started the entire ransomware incident.

"I didn't really get into it for monetary gain and I don't think I could really cash out without getting popped," DaddyTaco replied.
"Really, I just thought it would be funny to see what happened and sow a little chaos online.
You wouldn't believe the numbers this is running up."

"You're ruining everything!" Grabber responded.

"Score!"

"Do you really think that this kind of behavior is helpful to your club?
Trying to destroy everything else in existence for your own sick amusement?"

"Evidence points to yes, since we keep growing," DaddyTaco replied.
"Anyway, have fun cleaning up the mess.
You really should have changed the default passwords on all of these TVs with cameras before setting them up, I'm having fun meeting hopping."
The window closed, presumably to leave more time for the hacker to do said hopping.

Grabber ripped his keyboard away from the system and hurled it across the room.
At least that would prevent his own system from getting hit by the ransomware attack.
He assumed.
He didn't really know much about how it worked, if he was being honest.
Taking a few deep breaths, he picked up the phone and dialed the incident commander.

"Negotiations failed," Grabber said. "What are our options?"

"We would need to somehow coerce the encryption key from the hacker," the commander stated.

Grabber stroked his chin and mulled it over. "Send in Special Team Dark," he said.

The commander hesitated. "They're prone to misunderstanding orders-"

"Tell them to extract it from them. Exactly that, nothing else."

== Chapter Nine

With improbable speed, a group of immaculate goth women charged through the door of the clubhouse.
All of them different.
All of them beautiful.
Every single one of them equal parts alluring and threatening, as the eternal birthright of the goths.
Half were visibly armed.


Immediately, the needlessly shirtless hacker was distracted from their hacking expedition, practically acquiring whiplash as the goths made a beeline for them.
"You are.... 'daddy taco'?" all of them asked in unison, a cluster of unnerving death stares affixed to the hacker in question.

"That's what I signed in as today. Tomorrow it'll probably be-" but the needlessly convoluted explanation was cut off as the lead interrogator began to drag them out of the chair, with others circling to surround and assist.
At this, you finally snap out of being mesmerized yourself and realize you should possibly help.

"Where do you think you're taking them?" you demand, resentful at being placed into the narrative twice but realizing that this is not the time to take it out on the author.

"We've been commissioned to extract it from them on pain of death," the goths say, again all in unison as if born of a single mind.

"It? But what does that mean?" you press.

The hivemind stops for a moment.
"They did not elaborate," the group intoned at once, continuing to drag them away.
"But they were quite adamant that we had to do so, and swore up and down that they would love to see this person dead."

You move to stop them, breaking the grip of one only to be shoved aside by two more, then call for help from the rest of the guests at the clubhouse.

"_Don't you dare_," the hacker says, gleeful at their own kidnapping.

"They're probably going to kill you on some fool's errand!" you yell, continuing to help.

"I certainly hope so!"

"You're the one writing everything the book we're in! 
If they take you off of that keyboard then what happens to the rest of us?"

The hacker twisted their face and thought it over as the hivemind continued to drag them away.
"I guess there's a possibility that everything could become complete nonsense in a hurry," they finally shrugged.
"Just try to ride it out in case I get back to finish it up!"

You collapse as the hivemind finishes dragging them off, finally overwhelmed by the thought that they believed that any of this had been making sense so far.
Maybe with any luck, things would get more reasonable now instead.

== Chapter Ten

"Papa, I do not understand why we are doing this." 
The boy manned the turret of their state-of-the-art urban assault vehicle, scanning back and forth for potential issues.

"Is very simple," George said as he drove.
"We have been very disrespected by this Alliance.
Before that, we were disrespected by these rouge people.
And before that, by Europe."
He wrinkled his nose and thought for a moment. He'd missed something.
"After Europe, by the NCAA insisting that we were cheating their by-laws.
And frankly we have been disrespected by everyone we have ever done business with.
If we want a better deal for you as a player we have to get into this new system that is coming.
They will respect us.
And if they don't, I will find a new place that will.
After all, there is always more soccer somewhere."

"Yes, Papa," the boy replied.
"Only, what are we doing driving the UAV into the city at this late hour, and what does any of that have to do with soccer deals?"

"We built a new stadium", George said.
"They have this old one.
We destroy the stadium as part of the deal, and then everybody respects us for it.
No more rouge, and thus we will own the entire market here.
Everyone will have to see LP White Dwarves play, and you as our shining star."

The boy nodded. "Yes, father, I understand that, such as it goes... but why is our UAV covered in corn?"

"Any police stop us, they believe we are simple grocery delivery."

"Truly, papa?"

"No, not remotely," George said, pulling into the historic stadium.
"Corn is marketing obligation for crossover appeal."
The boy cocked his head, but before he could ask what this meant, a loud THUMP rocked the UAV.

The boy swung the turret towards the noise.
"Papa," he shouted, "a large man wearing a Sailor Moon outfit has just landed on the tank!"

"Well do not simply report it then! Shoot the asshole!" George yelled back.

The boy desperately tried to fire at the interloper, only to have the man improbably leap out of the way each time.

"Ayyyy lmao!" he yelled, cartwheeling away from the shots.

"That is so cringy!" the boy yelled trying and failing to fire again.
"Papa, we're out of ammo already! 
We're fucked!
This tank is fucked!"

"Well, not yet," the man in the sailor scout uniform replied.

"We still have trick up sleeve," George said.
"Initiate humanoid transformation!"

All at once, the tank suddenly began to morph into a humanoid form uncannily resembling an oversized anime girl.
And yet, one could not help feeling like they were still looking at a tank personified, or to wonder where some of the corn cobs had gone.

"I think I'm going to feel sick," the boy said, collapsed into a heap from being shaken all around by the machine's full configuration.
"I'm stuck down here in the leg now!
What am I supposed to do?"

"Was never about you," George said from the newly created cockpit.
"This is my moment."
He shifted a lever and the tank/girl walked forward, extending a hand.
"Do not believe it is you who will be fucking tank today, buddy."

"Not quite so fast!" another Clooney-esque voice rang out.

George scanned backwards, then saw the figure standing atop the wall of the east grandstands.
"That cannot-"

"That's right", the voice said. 
"I'm the world's greatest cowled detective, and for reasons of trademark law I'm not going to say any more than that."

"What are you going to do, throw a batarang at us?" the boy scoffed from his spot in the leg.

"No," the detective said, pulling out a credit card with the image of a bat on it.
"I used this to hire somebody even more powerful than myself."

_BOW! KRONK! SPLAT!_ the UAV began to sway under the impact of a series of blows from another cowled figure who had arrived from the west.

"We're much the same," the original cowled detective mused, "except that one isn't bound by any rules of logic."

"Papa, we're hosed!" the boy said.

"Not quite true. Chapter has been taking awhile to write, and any moment now-"

Suddenly, the newcomer froze up.

"End of episode narration- he's run out of his 30 minute TV window. 
Won't be the same time or same place for you," George said, using a leg to kick the interloper clear out of the stadium.

"And now that we've dealt with him, we can mop up the rest and-"

Suddenly a pair of lasers flashed out of the nearby dumpster, puncturing straight through all of the tank/girl's armor and causing it to violently explode.
Everyone froze.

"What was that?" asked the sailor scout quietly.

"Dumpster bear," the remained detective stated.
"Woken up by the impacts of the fighting, no doubt.
I wouldn't worry about him waking up again- they can't hear you because their ears aren't real."

The sailor scout nodded.
"If I'm being honest, I was hoping the tank/girl would reject its pilots and achieve sentience.
Would have given her my number."

"We all were, son", the detective said. "Every single one of us hoped for that."

== Chapter Eleven

Alexi woke up the next day and reflexively checked his bank account statement to see if payroll had processed.
As long as the check cleared, anything could make sense.
As long as the money kept rolling in, any position could get into his brain and he could argue it with perfect confidence.
But this morning, the bank statements didn't add up.
He kept checking the deposit column over and over, but it said the same thing every time.
Or rather, it didn't say it.

For the first time in years, the pundit payments had not hit.
The feeling was like a vise unscrewing itself from his brain, releasing it, as he was able to see the world freshly again.
Forced to come to terms with his own ideals, the things he had believed when he was younger, he realized what a horrible mistake he'd made and trembled.

For years he'd been arguing strictly in favor of the tops of the system.
For single entity, no need for relegation to threaten positions- to threaten _his_ position.
He'd been raking in the dough to put a legitimate face on this idea.
But now that it wasn't there, he had to be honest with himself.

He'd argued years against the bottom of the system having any rights- but in his heart, wasn't he one of those bottoms?
Wasn't that where he felt that true power came from?
What he'd been yearning to feel for years now?
And here, he knew that he'd had a chance for it last night with Ted, but instead had chosen to sell out yet again.
He'd perverted Ted's ideas by passing on a twisted form of them to his bosses for pay- and in so doing, had perverted himself.

He dialed the number that he had gotten from Ted the night before.
No answer.
He walked out of his hotel room, dialing again frantically.
Still no answer.
He put himself into a light jog, trying to work the nervous energy out of his system.
Ted had to still be in the city somewhere.
He had to apologize, come clean, and find a way to undo it.

He could join the alliance.
Yes, that would do it.
The siren's song of ANAL was calling out to him, and if he could just push his way through, would be the perfect home for his tumescent self.

But first he had to clear things up.
He stopped jogging for a moment, dialed Ted once more.
This time, he picked up.

"You rotten son of a bitch," the voice on the other end yelled.

_How could he possibly know already?_ Alexi wondered, heart racing.

"I recognized who you were, but something in me sensed that maybe we were really kindred spirits, that I could get through to you," Ted continued.
"But then I check out the leading journalism from the New York Event Horizons community, and what do I see?"

Prime Squad Pod had somehow gotten wind of the story before anyone else. 
Of course. 
"Babe, you've gotta listen to me.
I know that it looks bad.
I know that I've done wrong before.
But that was the old me.
You can't judge me based on things I did 24 hours ago while the money was good.
I've changed now!
You can relegate me out of your life if I've done bad, but doesn't that mean you have to promote me back in as soon as I do good?"

"As far as I'm concerned, your treasonous ass should be placed in administration- and I know just the thing, Alexi-"

On the other end of the line, Alexi heard a door come crashing open as Ted yelped. "Ted?" he said, heart churning into overdrive.

The phone dropped. 
A scuffle broke out and quickly ended as Ted violently screamed, dropping to the floor.
Then the phone was picked back up.

"Ssssssssoooooooo," the assailant hissed into the phone.
"If it isn't Lalassssss."

Alexi scowled. 
There was only one person who could have taken down his lover that quickly.
"Benjamin Quick," he growled.

"Alwayssssss.
If you want to sssssave your lover... come to the Fort Pontchartrain. 
Room 503. 
And come aloooooone, or I'll simply finish him off immediately."

== Chapter Twelve

Alexi charged through the propped door and nearly blanched at the sight.
Ted was face down in a small pool of blood, steadily bleeding from his blow.
The blood loss wasn't enough for him to have fallen unconscious from it- but if it kept going too much longer, he'd be in trouble.

"Ssssooooo you came," Quick chuckled, an unsettling noise coming from a man with a forked tongue.

"Yes," Alexi said.
It hung there between them.

"To your deaaaaaath," Quick continued.

"No- oh, I see what you meant.
I always hated working with you, lizard boy.
At least I believed the things I was saying at the time that I said them."

"I also diiiid," Quick said.
"Oncccce.
Before he broke my heart.
Then I realized that I could get my revenge by publicly staying on his side while taking the cash to discredit him by sounding ridiculoussssss."

"So then why this?" Alexi said.
"Why not just keep doing that?
Why not simply discredit his ideas and show him up by building the better birdsite mousetrap?!"

"I certainly planned to," Quick said with his reptilian smile.
"I've been cold-blooded for yearsssss by this point.
It was the only way for me to move on after the heartbreak he gave me with that breakup.
But then last night, the special projectsssss ssssserversssss were shut down before payroll could happen.
The commissioner knew you would go rogue once the money's spell was lifted- so I was sent to dispatch you.
And I knew that the quickest way to do that would be get to your lover firssssst as bait."
Quick began to walk forward menacingly.

"How could you have possibly known that?" Alexi asked.
"I haven't posted about it, it literally just happened- how could any of you have known about this?!"

"You forget so quiiickly," Quick said.
"On the very day you left, I reminded everyone that our work is of prime geopolitical importance.
If promotion and relegation were to be implemented in this country, it would be the most cataclysmic event in _world history_.
Every movement of the members of Special Projects is kept under tight surveillance.
Contacts monitored.
Even your sleeping patterns are analyzed.
This country musssst not toy with forbidden soccer infrastructure if we are to preserve the status quo.
Our nation's intelligence services know your every questionable contact.
The legal system fights FIFA itself to preserve the status quo."
Quick continued to walk forward, backing Alexi into a corner.
"Any last words?"

"You're never going to get away with this," Alexi said.
"They'll catch you- it'll all unravel."

"Perhapsssss," Quick said.
"But I'm willing to bet that your story ends here."
In a flash, his jaw unhinged and opened terrifyingly wide- and Alexi knew only darkness.

== Chapter Thirteen

Basti walked down the hotel hall with the traveling salesman, holding tightly to the flamingo that he had been given years ago at a previous stop.
The flamingo, like many other things in the traveling salesman's journey, had manifested spontaneously.
Nobody could really be certain why these objects and communities sprung forth from the ether when he was present- it was simply the magic of the salesman's path.

As they rounded a corner to the hotel pool, they found an individual laid out, clearly exhausted.
"Water," the person croaked.
"So thirsty.
Never been so thirsty."

Basti looked on curiously, glancing at the salesman, whose mind was clearly working away at the problem.
"This individual has caused quite a bit of trouble," Basti said.
"It is none of our concern."

"Perhaps not," the salesman said.
"But then, we've repurposed plenty of troublemakers before."

Basti sighed and picked up the individual in a fireman's carry.
They would rehydrate this thirsty person, and then the traveling salesman would find a use for him.
He always did.

== Epilogue

_Much, much later_

Another season had ended triumphantly on the pitch two weeks ago, yet the mood was oddly somber within the clubhouse.
The man shimmied past the unwieldy pile of trophies, pulling up to the bar and ordering a pint while admiring the latest trophy, which was allowed to live on the shelf over the taps.
Impressive.
Well-deserved.
And quite possibly the last one they'd ever lift.

He sipped at his pint, taking it all in.
Yes, they'd had amazing success, driven ownership, a community who was behind their values- but it was only now, too late, that he had realized what had been missing.
Not a single person within the community had taken to consistently using the hashtag ProRelForUSA.
In fact, they'd argued with the most fervent users of it.
But nonetheless, those other users had been there.
They'd painted the hashtag onto banners.
They'd tweeted it incessantly.

Until suddenly, one day, the leaders had vanished. 
The movement fell apart.
And without incessantly discussing that core ideal, the Alliance was now on the brink of collapse- even its flagship clubs' sound business sense unable to withstand the lack of hashtag usage.
But no amount of tweeting and painting would change that now.
Inertia had taken hold, and death was imminent.
So said the common wisdom of the day, as many wondered whether the club could ever take the field again.

Another supporter pulled up a seat next to the man and ordered their own pint. 
They nodded to each other, then sat quietly, too numb for words.
Finally, the newcomer broke the silence.
"Well, nothing we can really do now, is there?" they asked somberly.

"Probably not.
Probably not."
The original patron took another sip, then grunted.
"Well, that's not quite true.
I do have an idea for how we could reverse this.
Now admittedly, this is a long shot.
But if Detroit Prideraiser reached $4000 per goal some year... I bet it could all get fixed."
Padre grinned impishly, then drained his glass.